- client/apollo/js/View/Track/AnnotTrack.js
This is a feature that was requested in #124 
Functionally, it is hooking into jbrowse's layout algorithm and then applying a custom layout algorithm to collapse the features (i.e. it is just flat)
Comments welcome
> Feature yaxis merge

- build.xml
This is a proposed fix for #148 that copies the plugin to the jbrowse.download.directory instead of the webapp directory and only applies the filter to the js files
CC @deepakunni3 @nathandunn
> Fix golr urls

- client/apollo/css/main.css
- client/apollo/css/maker_darkbackground.css
- client/apollo/css/webapollo_track_styles.css
- client/apollo/js/View/Track/AnnotTrack.js
- client/apollo/js/View/Track/DraggableHTMLFeatures.js
- client/apollo/js/View/Track/SequenceTrack.js
- client/apollo/js/main.js
- src/main/webapp/changes.jsp
- src/main/webapp/recentChanges.jsp
- src/main/webapp/tracks.jsp
This pull-request is sort of a combination of several things aimed at 1.0.4. I can split this into separate pull requests if you want but there is actually overlap between various things (i.e. the (1) also involved considerations for (3))
1) a fix for #155 which tries to automatically resize track height, automatically sets showlabel=false when collapse is turned on, and actually, another idea i had, is when collapse is unselected and showlabels=true beforehand, then reenable showlabels=true. this hopefully makes the collapse features fairly "natural" however testing is needed
2) a  fix for #119 to make user-created annotations track teal when using dark theme. other small adjustments to dark theme includes (a) removing the small white border between tracks (b) making theme change …
> 1.0.4 various fixes

- grails-app/services/org/bbop/apollo/ExonService.groovy
- grails-app/services/org/bbop/apollo/FeaturePropertyService.groovy
- grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- grails-app/services/org/bbop/apollo/TranscriptService.groovy
This is request to turn off transactional reads and so it is a more lightweight optimization (compared to #460). This leads to some speedups
In a scaffold with 400 features, previously it would take 180 seconds. Now it takes 40 seconds. That is still not optimal but it is better because the nontransactional tag prevents the data from being re-fetched every time. 
Further optimizations will require doing some better querying, this change did not change any querying, only the tagging of methods as nontransactional
Note: I could not set @Transaction(readOnly=true) because having both @Transaction was set globally and the @Transaction(readOnly=true) set on a specific method produced the error "transactionManager is declared in a dynamic context, but you tried to access it from a static 
Note …
> Turn off transactional for read only methods

- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/NonCanonicalSplitSiteService.groovy
- grails-app/services/org/bbop/apollo/OverlapperService.groovy
Here is an initial fix for #531 
It does fix (in test cases that I had) the issues with sequence alterations miscalculating non-canon splice sites on the negative strand
Here are some remaining issues that are I think not big problems, but just notable.
- Haven't really tested deletions very much but seems to work if it's in an intron (doens't affect non canon splice site flags, a good thing)
- Insertions larger than 2 bp inside a splice site cause a string out of bounds exception (I am probably just overlooking something here)
- Non-canon splice sites exclamation marks are slightly off center in the plus strand features but they do seem to be calculated appropriately otherwise?
I just wanted to get this available for review ASAP, please test and comment :+1:
> Fixup non canon

- grails-app/conf/BuildConfig.groovy
- grails-app/domain/org/bbop/apollo/Feature.groovy
- grails-app/services/org/bbop/apollo/FeatureEventService.groovy
Fixes issue #555.  
@cmdcolin   
Can you test this / comment on any changes and we can go ahead and merge it (hopefully). 
The solution is to not go to the database constantly but use a "glob" of possible feature events pulled off of FeatureEvents . . but allows accounting for splits and merges.
> Feature feature events

- grails-app/migrations/changelog-2.0.1.groovy
This adds a precondition to the migration script to make sure that some changesets are only applied if upgrading from 2.0.0
See
#616
> Fix database migration for 2.0.1

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- grails-app/views/organism/chooseOrganismForJbrowse.gsp
Currently for jbrowse links we have to specify the organism ID which is not easy to memorize
This pull request makes us allowed to use the name of the organism for this purpose
So instead of just 
http://mysite.cool/Apollo2/jbrowse/index.html?organism=1351345
Which is impossible to memorize, we can now also have
http://mysite.cool/Apollo2/jbrowse/index.html?organism=Honeybee
Note that our command line tools have allowed using name instead of organism ID for awhile now, so at least conceptually this is not new.
This was kind of discussed in #618
> Add ability to set organism by common name in URL

- docs/Apollo2Build.md
- grails-app/domain/org/bbop/apollo/Feature.groovy
- grails-app/services/org/bbop/apollo/OrganismService.groovy
See #636
This commit takes a different approach towards deleting features from an organism
It selects features from an organism using criteria queries, and then simply uses hibernate functions instead of raw SQL, which I think is much more elegant.
It also does away with the fetchMode join in Feature.groovy. We have talked about fetchMode fairly frequently but I think it breaks the Feature objects stability
> Delete features from organism

- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/conf/BootStrap.groovy
- grails-app/conf/Config.groovy
- grails-app/controllers/org/bbop/apollo/ProxyController.groovy
- grails-app/services/org/bbop/apollo/DomainMarshallerService.groovy
- grails-app/services/org/bbop/apollo/ProxyService.groovy
- grails-app/views/proxy/_form.gsp
- grails-app/views/proxy/show.gsp
For #148  . . . 
From the issue itself:
>http://golr.geneontology.org/select?q=*:*
>http://golr.berkeleybop.org/select?q=*:*
>http://golr.berkeleybop.org/solr/select?q=*:*
>The first two are "forever" URLs, with the first being the "production"
>one and the second being a special use one (failback, some experiments,
>etc.). The last one there is functional for the time being, but is on
>notice--it should be replaced in all code going forward with the first
>(this has been harmonized with production, so we should be good in the
>future during outages and the like). At a future date, the third should
>be purged at version EOL
This code allows a "fallback" if the other one goes off-line that can be affected without a redeploy, though  this has to be set manually right now. 
At some point we …
> #148 - made urls more configurable for GOLR

- grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
- grails-app/views/featureEvent/changes.gsp
This adds a sequence column to the recent changes page
We have planned more additions to the recent changes page (bulk operations) but this is the most basic implementation of such a feature!
> Add sequence names to the recent changes page

- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- restapidoc.json
- web-app/js/restapidoc/restapidoc.json
Fixes #776 
- the webservices "live" api docs in apollo don't seem to be regenerated. Is there a way to do that? (Or maybe this is a caching issue locally)
- do I need to add unit tests of any sort?
> Expose setName feature

- client/apollo/css/main.css
- client/apollo/css/maker_styles.css
- client/apollo/js/main.js
The maker2jbrowse script uses jbrowse specific track styles (which are based on pixel heights) and Apollo uses percentage heights
This adds an "apollo specific" style set that helps style the features loaded with maker2jbrowse
Before
After
> Fixed Apollo styles for features loaded with maker2jbrowse

- client/apollo/css/maker_styles.css
By default Apollo picked up this weird feature style from jbrowse which had these blue/grey alternating lines.
The blue/grey alternating lines was from a background-image in CSS, and this pull request simply removes that
Before
After
> Remove the blue/grey alternating lines from the default flatfile-to-json loaded tracks

- grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
- grails-app/views/featureEvent/changes.gsp
This applies a fix to keep track of the filter parameters during sorting so that it remembers the filters after applying a sort on the columns of the table
> Add filters parameter to the recent changes page. See #824

- grails-app/controllers/org/bbop/apollo/SequenceController.groovy
- src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
- src/gwt/org/bbop/apollo/gwt/client/dto/SequenceInfo.java
- src/gwt/org/bbop/apollo/gwt/client/dto/SequenceInfoConverter.java
Here is an example of adding annotation counts to the refseq panel
Address #803 
This doesn't have sorting on the annotation column yet, but I just wanted to put this pull request in place for review
> Add annotation count to the refseq panel

- grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- test/integration/org/bbop/apollo/Gff3HandlerServiceIntegrationSpec.groovy
This fixes an oversight pointed out in #836 and adds back repeat regions/transposable elements in a separate query (it is separate because the single features dont need complex parent/child relationships to be located)
I also added a integration test for this case as well and check for a repeat region in gff3 output
> Add repeat region/transposable element/seq alterations to the gff3 output

- client/apollo/css/webapollo_track_styles.css
- grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
- test/integration/org/bbop/apollo/Gff3HandlerServiceIntegrationSpec.groovy
This addresses #754
Adds residue exports to the substitution/insertions
It also adjusts some CSS because the substitutions weren't showing up (due to the remove_chevrons change)
> Add residue export

- grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
- grails-app/domain/org/bbop/apollo/FeatureLocation.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
This is a special query that optimizes the annotator panel for #820
It does a two step query
1. Get the genes in a specific range for the sidebar
2. Get the details about the genes in that specific range
This blog nicely summarizes that issue http://floledermann.blogspot.com/2007/10/solving-hibernate-criterias-distinct.html (briefly, the first step doesn't use select distinct() and the second one does)
We also have a "convertFeatureToJSONLite" for the purpose that avoids getting extraneous feature info, but even if we did want to display that info, we would still do well by using this strategy
I get about ~300ms for selecting new pages (mean 311ms, stddev 14ms) with database that is bulkloaded with over 10000 genes
Same database on  current master (mean 4528ms, stddev 775ms), so it's …
> Annotator panel optimization

- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- restapidoc.json
- web-app/js/restapidoc/restapidoc.json
Fixes #829 
Adds the following API routes:
- updateAttributes
- deleteAttributes
- addDbxrefs
- updateDbxrefs
- deleteDbxrefs
Should be working fine, but I'd appreciate a sanity check on this.
> Expose non primary dbx refs

- client/apollo/js/View/Track/AnnotTrack.js
Replaces the native javascript confirm box (which is likely to be blocked by the web browser) with a dijit dialog while asking users for confirmation at the time of delete annotations.
See #851
> Replace native confirm box with dijitDialog

- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/SequenceService.groovy
I found several places for optimizing FASTA exports with regards to #854. With the pythium data (340 genes), the time taken is now down to about 25s with this PR (repeated runs 28s,23.7s,22.7s)
Therefore, this new method is about ~16x faster
Some notes
1) This stops using SequenceChunks table. SequenceChunks does not really do anything for us compared with just reading the sequence from file. As a comparison, if I add back SequenceChunks, then the times are ~5x longer than without it (takes 1m59s,1m52s). Still better than 6min30s for export, but again, we don't really need to query database for those chunks.
2)  The getResiduesFromFeature had support for multiple feature locations, but it did something weird where if one of the feature locations was on the negative strand, then all of the …
> Speedup fasta export

- grails-app/migrations/changelog-2.0.2.groovy
- grails-app/migrations/changelog.groovy
This adds a stripped down groovy changelog-2.0.2.groovy and addresses #848
One important thing to note is that the createIndex command here requires "unique":false, because I tried it with true and then found some errors. I imagine it's because the history contains multiple entires for each feature's uniqueName
Some of the basic testing cases mentioned in #848 may need to be addressed but I figured I would get this code out there.
> 2.0.2 new changelog

- grails-app/controllers/org/bbop/apollo/SequenceController.groovy
This is a bug that is similar to #862, because every time the login screen is presented, the GWT calls getSequences anyways, which fails with this error
```
2016-02-09 09:56:05,269 [http-nio-8080-exec-24] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [POST] /Apollo202mod/sequence
/getSequences/
Named parameter [organism] value may not be null. Stacktrace follows:
java.lang.IllegalArgumentException: Named parameter [organism] value may not be null
at org.bbop.apollo.SequenceController.$tt__getSequences(SequenceController.groovy:187)
at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
at …
```
> Fix error when getSequences is called during login

- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/SequenceService.groovy
- test/integration/org/bbop/apollo/SequenceServiceIntegrationSpec.groovy
Currently the FASTA export still seems to have bottlenecks, and I was seeing it take a very long time on the honeybee datasets with only modest amounts of genes (with 172 genes, it took over 14 minutes and sometimes never finished).
I looked at the flamegraph and found that the main time that was being taken up was during getSequenceAlterationsForFeature
Specifically, there is a step where hibernate appears to want to flush some data before calling the HQL. As a workaround, simply disabling this "flush" step saves a lot of time during exports.
Before this fix, as reported in #858, time for exporting FASTA on 341 pythium genes took ~24 seconds, now it takes about ~5 seconds (see graph below)
This seems modest, but for honeybee, the gains are more dramatic, over 14x faster, and sometimes, …
> Optimize FASTA even further

- src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
I was testing #872 on a bunch of different platforms and found that the top of the annotator panel did not show up in IE11 on Win7
This issue with the annotator panel and IE11 also seemed to affect WA2.0.1.
The reason for the bug is that the form elements were being rendered in weird places off the screen entirely.
I made a fix for this that that changes "display: inline-table" to just use "display:inline", so now it appears fixed.
> Fix error with annotator panel on IE11

- src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
I found that the OS added a default background-color: white when the select box was selected, and since text color was white, it created the effect seen in #870 
This PR just adds the background-color: gray when element is focused
> Fix white background on select box. See #870

- client/apollo/js/View/Track/WebApolloCanvasFeatures.js
The tRNA option was missing from the canvas features as reported in #868. ncRNA was missing too, so that is added back as well. The order matches the order on the DraggableHTMLFeatures.
> Add full feature list to WebApolloCanvasFeatures. See #868

- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
This PR addresses a bug that seemed to affect IE10 but has a fairly logical solution, which is to specify the column widths more accurately. See #877
> Fix error with table cells in annotator panel

- grails-app/services/org/bbop/apollo/FeatureService.groovy
@cmdcolin   Can you take a quick look at this to confirm?   
I tested it via an export of a fully annotated export of a gff3 (including GFF3).  Fixing this allowed the export.
Thanks.
> #844 was adding a json object as a database table

- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
- src/gwt/org/bbop/apollo/gwt/client/UserPanel.java
Currently when you visit an Apollo instance, several requests for web services are launched when the user is not logged in which creates errors in the javascript console and in the catalina logs
Javascript console
```
XMLHttpRequest.java:305POST http://localhost:8080/apollo/user/loadUsers/ 401 (Unauthorized)
JSONParser.java:200Uncaught java.lang.IllegalArgumentException: empty argument
XMLHttpRequest.java:305POST http://localhost:8080/apollo/user/loadUsers/ 500 (Internal Server Error)
XMLHttpRequest.java:305POST http://localhost:8080/apollo/group/loadGroups/ 500 (Internal Server Error)
```
Server logs
```
2016-02-19 16:30:19,273 [http-bio-8080-exec-9] WARN  apollo.AnnotatorController  - Permission exception: User has no access to an organism and/or is not admin
| Error 2016-02-19 …
```
> Avoid creating requests to web services when user is not logged in

- client/apollo/css/maker_styles.css
The current draggable alignments style was modified when we made the maker2jbrowse patch. I'm reverting some of that change, which reduces the prettyness of maker2jbrowse style a bit, but that can be addressed later most likely.
Ref #785
> Fix draggable alignments style

- client/apollo/css/maker_styles.css
- client/apollo/js/main.js
This updates the fixes in #897 to preserve the improved styles on track features from #785
This also creates a config option called "overrideApolloStyles" which can, in the event of a "CSS emergency", disable the entire stylesheet, and go back to having the chevrons and whatnot.
Screenshot with RNA-seq BAM and features
> Add style for fixing both bam reads and transcripts

- client/apollo/js/View/Track/WebApolloCanvasFeatures.js
Checks for the dark theme and creates special styles on CanvasFeatures tracks
Note that it uses this "Util.deepUpdate" which is a nice way where the user can override the config in their trackList.json, but we supply the default value in _defaultConfig
> Use more readable colors for canvasfeatures dark theme

- client/apollo/js/View/Track/AnnotTrack.js
In the SPARQL thread, we had examples of a SPARQL query that created features without subfeatures, which was something Apollo rejected.
Reasons it rejected it
- it would assign fmin and fmax to undefined
- it would not initialize a needed subfeature used for calculating the ORFs
This fixes fmin/fmax and initializes a subfeature to allow the bare features to be annotated
Ref #827
Note this scenario is basically the same as the CDS with no parent on the volvox sample browser http://jbrowse.org/code/JBrowse-1.11.6/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A2376..24986&tracks=DNA%2Cvolvox_vcf_test%2CCDS&highlight=
> Make Apollo work with 'bare' features without subfeatures

- apollo
This sets up a "watchman" when using standard apollo development commands.
The watchman software checks for filesystem changes and in this case runs script/copy_client.sh
This helps client side plugin development by not having to manually copy over files
> Add watchman configuration

- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
There is a bug when updating or adding multiple feature properties at once where it would use the wrong loop counter.
> Fix error when adding or updating multiple feature properties at once

- .jshintrc
- .travis.yml
- client/apollo/js/EUtils.js
- client/apollo/js/FormatUtils.js
- client/apollo/js/SequenceSearch.js
- client/apollo/js/Store/SeqFeature/ScratchPad.js
- client/apollo/js/View/Track/AnnotTrack.js
- client/apollo/js/View/Track/AnnotTrackSocket.js
- client/apollo/js/View/Track/DraggableHTMLFeatures.js
- client/apollo/js/View/Track/DraggableResultFeatures.js
- client/apollo/js/View/Track/SequenceTrack.js
- client/apollo/js/main.js
Adding a basic syntax checker to the javascript can help catch syntax errors. In fact, running it over the current codebase caught a number of minor issues. None were critical. The rules for jshint are not super strict, and basically match those on GMOD/jbrowse.
Also retabbed several files (standardize on spaces, not tabs)
> Add jshint checker for client side plugin

- sample-h2-apollo-config.groovy
- sample-mysql-apollo-config.groovy
- sample-postgres-apollo-config.groovy
I thought it would be good to have an example of modifying the configurations directly in apollo-config.groovy rather than having to modify grails-app/conf/Config.groovy.
This PR therefore adds two example customizations (1) adding debug logging for the development environment as an example of customizing the logging (2) adding an apollo.gff3.source parameter as an example of customizing the main apollo config
> Modified apollo config

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
In 2.0.1 we allowed adding a link to public jbrowse mode only using &organism=hg19 for example
When they logged in after visiting a link with this URL format, it failed to work (#845) so this fixes that scenario in particular.
> Add fix for using organism=organismName

- apollo
- build.xml
- grails-app/migrations/changelog.groovy
#941 discusses a scenario where builds were breaking during release mode, which includes jbrowse build (which we had targetted using "dev" versions of the build artifacts, but those were renamed, breaking the build. this just retains the naming).
> Update release build rules to fix #941

- sample-h2-apollo-config.groovy
- sample-mysql-apollo-config.groovy
Currently at master branch, the sample config files for H2 and MySQL has configuration lines for a Chado data source. This PR removes these configurations since Chado will not be compatible with H2 and MySQL.
> Remove Chado data source configuration for H2 and MySQL

- src/templates/war/web.xml
Uses top answer from here
http://stackoverflow.com/questions/2907516/how-to-configure-a-session-timeout-for-grails-application
This PR increases the default session timeout to be equal to two days (48 hours)
I think that we do not have large concerns about user's sessions taking up too much memory, and we are not a bank that "requires" logging someone out after 30 minutes, so I see no downsides for extending the session by default. 
This PR helps both public jbrowse mode and logged in annotators.
Note: on #493, we could still "trigger the logout code" if session timeouts, and this might be similar to how bank sites operate, but I think generally, just making the session longer makes a lot of the noticeability of this problem go away.
Ref #493 #978 
Screenshot of tomcat manager after this …
> Add longer session timeout by default

- client/apollo/js/View/Track/AnnotTrack.js
I tried to edit a feature from master, failed with
```
| Error 2016-04-25 18:02:07,965 [http-bio-8080-exec-8] 
ERROR apollo.AnnotationEditorController  - 
org.codehaus.groovy.grails.web.json.JSONException: JSONObject["clientToken"] not found.
```
> Missing client token on opening of feature editor panel

- apollo
This aims to fix #1017 
The general issue would be that watchman did not have the right permissions in that case, and is confusing.
In general watchman is only useful for development modes so we can take it out of general usage
> Only use watchman with explicit command

- docs/Apollo2Build.md
This PR adds instructions for users to download a specific version of Apollo during the Quick-start guide.
This change is made with the intention to get users to use stable releases instead of master branch, which although sometimes helpful (they catch bugs....) it is not nice to test our master branch on our newest users
I had thought it might be nice to automatically populate this version information from a config but instead this info would have to be manually updated when new versions are released.
> Add instructions to download the specific version

- grails-app/services/org/bbop/apollo/ChadoHandlerService.groovy
- src/gwt/org/bbop/apollo/gwt/client/ExportPanel.java
- src/gwt/org/bbop/apollo/gwt/client/rest/SequenceRestService.java
This PR adds the functionality to provide user with the option to limit their Chado export to only those sequences that have annotations, to Chado.
This PR also improves the speed of export when exporting all sequences for an organism.
> Chado export ui tweak

- grails-app/services/org/bbop/apollo/FeatureService.groovy
- src/groovy/org/bbop/apollo/sequence/Strand.groovy
- test/integration/org/bbop/apollo/FeatureServiceIntegrationSpec.groovy
Address the issue where when a feature (that has no strand information) is added as an annotation, Apollo will default it to the sense strand.
Fixes #873.
> Enforce strandedness for features that don't have strand

- build.gradle
FYI @erasche   this PR should fix plugins being installed properly on master.  
You have to define the ```apollo-config.groovy```:
```
plugins {
WebApollo{
included = true
}
NeatHTMLFeatures{
included = true
linearGradient = 0
}
NeatCanvasFeatures{
included = true
}
RegexSequenceSearch{
included = true
}
HideTrackLabels{
included = true
}
MyVariantInfo {
git = 'https://github.com/GMOD/myvariantviewer'
branch = 'master'
alwaysRecheck = "true"
alwaysPull = "true"
}
SashimiPlot {
git = 'https://github.com/cmdcolin/sashimiplot'
branch = 'master'
alwaysPull = "true"
}
}
```
> fixed git deploy of plugins

- docs/Apollo2Build.md
Thought it would make sense to tell users to install Gradle via `sdk` in the quick-start guide.
> add gradle installation to quick start guide

- apollo
- docs/Apollo2Build.md
- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
On some older java versions an NPE getServletPath fails.  This fixes that.
> Fixes bower installation and check for NPM, add JVM version 

- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/conf/Config.groovy
- grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- grails-app/controllers/org/bbop/apollo/CannedKeyController.groovy
- grails-app/controllers/org/bbop/apollo/CannedValueController.groovy
- grails-app/domain/org/bbop/apollo/CannedKey.groovy
- grails-app/domain/org/bbop/apollo/CannedValue.groovy
- grails-app/views/cannedKey/_form.gsp
- grails-app/views/cannedKey/create.gsp
- grails-app/views/cannedKey/edit.gsp
- grails-app/views/cannedKey/index.gsp
- grails-app/views/cannedKey/show.gsp
- grails-app/views/cannedValue/_form.gsp
- grails-app/views/cannedValue/create.gsp
- grails-app/views/cannedValue/edit.gsp
- grails-app/views/cannedValue/index.gsp
- grails-app/views/cannedValue/show.gsp
- src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
- test/unit/org/bbop/apollo/CannedKeyControllerSpec.groovy
- test/unit/org/bbop/apollo/CannedValueControllerSpec.groovy
Initial foray into #86.   This is pretty basic, but we can get fancier later.  
FYI @childers , @mpoelchau, @monicacecilia 
We have canned keys and canned values.   They are related.  
They are filtered by type.  Having a key with related types is "difficult", though possible.  Let's see where this gets us.  
You use the admin interface to edit the Canned Keys and Canned Values, similar to the Canned Comments.
> Canned key attributes

- grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
Fixed problem that the system was trying to issue a redirect when no redirect was requested (i.e., no params.targetUri was specified).  This was messing up some web services.
> fixed problem when issuing a redirect

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
Fixes #1187 . 
@deepakunni3  Can you check this when you have a chance.  
In the jbrowse sample_data directory plugins are of the form:
```
"plugins" : [
"NeatHTMLFeatures",
"NeatCanvasFeatures",
"HideTrackLabels"
]
```
though we explicitly support this format:
```
"plugins" : [
{
"location" : "./plugins/WebApollo",
"name" : "WebApollo"
}
],
```
This PR should allow supporting both.
> allowing for older version of plugins

- README.md
- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/controllers/org/bbop/apollo/LoginController.groovy
- grails-app/services/org/bbop/apollo/PermissionService.groovy
This handles the error @monicacecilia  found in #493 and also handles loadGroups and loadUsers without a username (like when logged out) with a 401 instead of a 500.  
@deepakunni3  Can you look at this when you have some time.   You should confirm that when you log out of one screen, that it logs out of ALL of them.
> Fix session logout code

- client/apollo/js/JSONUtils.js
- test/integration/org/bbop/apollo/FeatureServiceIntegrationSpec.groovy
Fixes #1308 
The issue was in `JSONUtils.createApolloFeature()` where all UTRs were explicitly being converted to exons.
> Fixes bug where Apollo client interprets 5'UTR and 3'UTR features as exons

- client/apollo/js/SequenceSearch.js
When we query the genome with BLAT, the result shown in the table displays the hit-start and hit-end incorrectly. Specifically, its always off by 1.
When BLAT is used for search, and if the output requested from BLAT is a tab-delimited format then the coordinates reported by BLAT will always be 1-based. This is the case for the configurations used in Apollo.
This PR aims to fix this tiny issue.
> BLAT search results shows incorrect start and end of the search results

- grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy
A small patch that fixes the problem described in #1423 (probably just a typo?)
> Fix REMORE_USER authentication with galaxy (#1423)

- grails-app/services/org/bbop/apollo/PermissionService.groovy
- grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy
Hi,
As discussed in https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment/issues/6, a patch to add a new param for RemoteUserAuthenticatorService to allow adding automatically new users to a group.
I don't know if it's the best way to implement it, but it works :)
Anthony
> Add new 'default_group' param for remote_user auth

- grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
- src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.java
- src/gwt/org/bbop/apollo/gwt/client/rest/AnnotationRestService.java
Fixes #1428 
To test:
Create the following types of annotations:
* gene
* pseudogene
* tRNA
* rRNA
* snRNA
* snoRNA
* ncRNA
* rRNA
* miRNA
* repeat_region
* transposable_element
From the Exon Detail Panel,
1. Modifying the boundaries of exons (and only exons) should properly be reflected in the rendering of the annotation. This is applicable for gene, pseudogene and all *RNA features.
2. Make sure that you cannot modify CDS boundaries from the Exon Detail Panel.
3. Make sure that Exon Detail Panel doesn't show up for repeat_region and transposable_element.
> Refactor updateFeatureLocation method in AnnotatorController to better handle updates to exon boundaries when a request is sent from GWT-land

- client/apollo/css/maker_darkbackground.css
Address #1437 - UTR colors and Intron colors for .Dark theme.
Requires JBrowse commit: https://github.com/GMOD/jbrowse/commit/29795a1bbb8da4706eba2b0f73724ac1b3e1e4e6
> Add .Dark styling for NeatHTMLFeatures

- grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
> Allow building public URLs to specific features

- src/gwt/org/bbop/apollo/gwt/client/Annotator.java
Fixes #1487 by explicitly checking the return value.  
@abretaud  If it returns anything besides the appropriate response it *SHOULD* ask you to reload. 
However, I haven't tested it with REMOTE_USER.    I can test it later this week with REMOTE_USER or if you have a chance to test this fix that would be great (just a one-liner).  
Thanks.
> fixes #1487

- client/apollo/js/View/Track/AnnotTrack.js
- src/gwt/org/bbop/apollo/gwt/client/Annotator.java
- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
- src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
- src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
- src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
@deepakunni3   Can you take a look at this when you have a chance. 
Basically, this uses the API directly to handle navigation in cases where you don't change organisms (e.g., navigating to a location or a sequence).     The exception is that when double-clicking the sequence panel, it handles it as an organism change.
> added a less jarring way to navigate between sequences and locations

- docs/Configure.md
- src/groovy/org/bbop/apollo/sequence/search/blast/BlastCommandLine.java
- src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
I updated the configuration to better show what the file would look like.
@deepakunni3  I don't think that blastn uses a databaseId argument.  blat uses it to specify the chromosome, but I don't think that the same is true for blast.  The result was that if you had the "search all genomes" box checked it would work, but otherwise would fail (for blast, works fine for blat).
@monicacecilia  You should be able to pass these instructions along.
> better blast configuration instruction

- grails-app/services/org/bbop/apollo/CdsService.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
> Account for pre-existing stop_codon_read_through when recalculating longest ORF after adding/deleting sequence alterations

- grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
- grails-app/controllers/org/bbop/apollo/AvailableStatusController.groovy
- grails-app/controllers/org/bbop/apollo/CannedCommentController.groovy
- grails-app/controllers/org/bbop/apollo/CannedKeyController.groovy
- grails-app/controllers/org/bbop/apollo/CannedValueController.groovy
A first try at implementing the REST API we talked about in #1507, for the moment for the Status only.
@nathandunn if you have 5 minutes, maybe you can tell me if it's what you had in mind?
It's not yet working (perm problem on showStatus, other error on createStatus), but I thought I could open the PR now, and see if I'm on the right direction
> Add REST API for availableStatus and canned comments/keys/values

- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
- grails-app/controllers/org/bbop/apollo/SequenceController.groovy
- grails-app/controllers/org/bbop/apollo/UserController.groovy
- grails-app/jobs/org/bbop/apollo/CleanupPreferencesJob.groovy
- grails-app/services/org/bbop/apollo/AnnotatorService.groovy
- grails-app/services/org/bbop/apollo/DomainMarshallerService.groovy
- grails-app/services/org/bbop/apollo/JbrowseService.groovy
- grails-app/services/org/bbop/apollo/PermissionService.groovy
- grails-app/services/org/bbop/apollo/PreferenceService.groovy
- grails-app/services/org/bbop/apollo/authenticator/UsernamePasswordAuthenticatorService.groovy
- src/groovy/org/bbop/apollo/sequence/SequenceLocationDTO.groovy
- src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java
Fixing performance and other issues for preferences.
Should grab from session based on the token and not go to the database unless it is not there (and then store it in the session if so).  
These may likely be identical (maybe we don't need to specify the token?) since this may be regenerated each time.  Its a little unclear as we want different tokens between tabs AND browsers. 
This should increase performance and decrease DB load and eliminate query loads.
> started to add fetching preferences from session - not ready to merge

- client/apollo/js/View/Track/AnnotTrack.js
This was due to the fact that the client was sending the leftExon and the rightExon in the wrong order when the scaffold was in reverse complement. This confused the splitTranscript logic.
The method `sortAnnotationsByLocation` in `AnnotTrack.js` was modified as a solution.
Many other operations including merge transcript relies on this method. So this should fix any odd behavior seen with merge operations as well.
Fixes #1622
> Fix bug in split operation when in reverse complement view

- client/apollo/js/JSONUtils.js
> Use 'id' attribute for name in feature JSON, in the absence of 'name' attribute

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
- grails-app/services/org/bbop/apollo/RefSeqProjectorService.groovy
- test/integration/org/bbop/apollo/RefSeqProjectorServiceIntegrationSpec.groovy
Fixes #1649 
So this was due to a bug in the way the sequence string itself was being handled in reverse complement view.
After fixing the bug I end up with the following view:
Now the forward strand and the reverse strand are as expected. 
Even the protein translation is correct. 
But still not there yet. The CDS frame has changed from 0 (in normal view) to 2 (in reverse complement view).
> Fix reverse complement view

- client/apollo/js/View/Track/SequenceTrack.js
Fixes `optimistic locking failed` error, as reported in #1665.
This was due to the add operation being called twice.
> Fix redundant update operation when adding sequence alterations

- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- grails-app/domain/org/bbop/apollo/Organism.groovy
- grails-app/services/org/bbop/apollo/AnnotatorService.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/OrganismService.groovy
- grails-app/services/org/bbop/apollo/SequenceService.groovy
- src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
- src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/dto/OrganismInfo.java
- src/gwt/org/bbop/apollo/gwt/client/dto/OrganismInfoConverter.java
- web-app/js/restapidoc/restapidoc.json
Fixes #95  for having a per-organism translation table.
@deepakunni3  Can you review when you have a moment.
> override the default translation table

- client/apollo/css/webapollo_track_styles.css
Fixes #412 
@childers  If you have a chance to look at this and let us know if similar matches for .cigarE / .cigar? would be helpful. 
This is a pretty simple fix.  You can also issue a separate PR / patch. 
@deepakunni3  I think this is ready for review.   Not sure what the history of why this wasn't done in the first place (in WA1) as it was pretty easy.
> added better coloring for strand matches

- grails-app/services/org/bbop/apollo/FeatureService.groovy
Fix cascade bug when changing annotation type of a feature that has a read through stop codon.
Fixes #1689
> Fix for #1689

- client/apollo/css/flat.css
- client/apollo/css/main.css
- client/apollo/css/maker_darkbackground.css
- client/apollo/css/webapollo_track_styles.css
- client/apollo/js/main.js
Needed a break from the debugging I've done for the past N days so here's a patch for some extra theme options.
Previously the "dark" theme looked like this. The bright yellow annotator bar always somewhat irked me
And the very bright sequence track
Additionally some labels were hard to read (e.g. Max Height Reached) and the wig track backgrounds was very light.
And a more muted sequence track:
Additionally I've added a "Flat" theme option (works with dark and light).
This option removes the gridlines (which I personally find distracting but all my coworkers say they cannot live without) and adds some box-shadows
> Dark Theme Touchups + Flat Theme Option

- .travis.yml
node needs version 5 or greater during the build process and we need to output the version
> added specific node version

- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- web-app/js/restapidoc/restapidoc.json
@nathandunn FYI
Cannot delete organism on 2.0.7 due to changes made to `/deleteOrganism` endpoint while working on Remote Upload feature.
This PR aims at safely fixing the issue in `/deleteOrganism` endpoint in OrganismController.
> Fix deleteOrganism endpoint in OrganismController

- apollo
- build.gradle
- tools/data/add_features_from_gff3_to_annotations.pl
- tools/data/add_transcripts_from_gff3_to_annotations.pl
This PR is an effort at fixing the issues with bowerless git plugin acquisition; notable changes:
apollo:
the function `check_rest_api` has been slightly modified to address a testing issue; the prior conditional checked for the existence of a json file that is already included in the repo; however, the rest-api-docs do not get generated on the first run of `apollo test`. changing the check to the `target` directory ensures this runs initially -- though it might be prudent to remove the check altogether and just compile the rest-api-docs to avoid the whole issue. 
also, the command `$grails_executable rest-api-doc` raised an error that asks the user to select the package they want to install, which in actuality is 'doc' -- hence the change to `$grails_executable doc`
build.gradle:
an …
> Jbrowse plugin git methods and test fixes

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
- grails-app/services/org/bbop/apollo/TrackService.groovy
This is just to fix the warning we see everytime we do `run-local` or `deploy`.
```
| Compiling 339 source files
| Warning The [removeIncludedPlugins] action accepts a parameter of type [org.codehaus.groovy.grails.web.json.JSONArray] which has not been marked with @Validateable.  Data binding will still be applied to this command object but the instance will not be validateable.
def removeIncludedPlugins(JSONArray pluginsArray) {
^
| Compiling 339 source files.....
***
```
Since `removeIncludedPlugins` is not an action within JBrowseController, I moved it to TrackService.
> Fix warnings by moving removeIncludedPlugins to TrackService

- client/apollo/js/JSONUtils.js
- client/apollo/js/Store/SeqFeature/BAMCombination.js
- client/apollo/js/Store/SeqFeature/Combination.js
- client/apollo/js/Store/SeqFeature/Mask.js
- client/apollo/js/Store/SeqFeature/QuantitativeCombination.js
- client/apollo/js/Store/SeqFeature/SNPCoverage.js
- client/apollo/js/Store/SeqFeature/_RemoteCombinationMixin.js
- client/apollo/js/View/Track/Combination.js
- client/apollo/js/View/Track/RemoteAlignments2.js
- client/apollo/js/View/Track/RemoteDraggableAlignments.js
- client/apollo/js/View/Track/RemoteDraggableHTMLFeatures.js
- client/apollo/js/View/Track/RemoteFeatureCoverage.js
- client/apollo/js/View/Track/RemoteSNPCoverage.js
- client/apollo/js/View/Track/RemoteWebApolloCanvasFeatures.js
- client/apollo/js/View/Track/RemoteWebApolloCanvasVariants.js
- client/apollo/js/View/Track/RemoteWebApolloHTMLVariants.js
- client/apollo/js/View/Track/WebApolloCanvasVariants.js
- client/apollo/js/View/Track/WebApolloHTMLVariants.js
- client/apollo/js/View/Track/Wiggle/RemoteDensity.js
- client/apollo/js/View/Track/Wiggle/RemoteXYPlot.js
- client/apollo/js/View/Track/_RemoteCanvasMixin.js
- client/apollo/js/View/Track/_RemoteHTMLMixin.js
- client/apollo/js/View/Track/_WebApolloVariantDetailMixin.js
- client/apollo/js/main.js
@nathandunn This is ready for testing and review (but not ready to merge).
This PR introduces new track types (and stores) which are automatically registered and applied when a file is opened via the File -> 'Open track file or URL'.
When a local file is opened in the original forward orientation, the features will show up as usual:
When a local file is opened in a reverse complement orientation you will see the following:
This PR also adds combination track support for native Apollo tracks (such as DraggableHTMLFeatures) which were not supported before.
> Issue 1732 - support File -> Open

- client/apollo/js/TrackConfigTransformer.js
- client/apollo/js/View/Track/WebApolloAlignments2.js
Extend `JBrowse/View/Track/Alignments2` to support the ability to create an annotation from reads. The annotation can be created via Right-Click -> Create New Annotation -> Select the feature type.
The logic is similar to `WebApollo/View/Track/WebApolloCanvasFeatures`.
> Add a WebApollo version of Alignments2 track type

- grails-app/controllers/org/bbop/apollo/GroupController.groovy
"empty" permissions for organism are handled funny (client shows them, but user has no permission).  They should be removed, instead, similar to the user permissions.
> remove permission if empty

- apollo
The method for determining the javac version fails if for example JAVA_TOOLS_OPTIONS is set because javac will display that too. The change to check_java() tightens up the process so that unexpected output from javac is ignored.
> Determine javac version more robustly

- grails-app/controllers/org/bbop/apollo/UserController.groovy
- src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
- src/gwt/org/bbop/apollo/gwt/client/UserPanel.java
- src/gwt/org/bbop/apollo/gwt/client/dto/UserInfoConverter.java
- src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java
- web-app/js/restapidoc/restapidoc.json
> Handle large user set

- README.md
Just a quick fix in README.md that make hyperlink on Travis Badge better.
Originally, the link points to the svg image itself.
Now, it links to the current build page of master branch on Travis.
> Update the travis badge in README.md

- client/apollo/js/ProjectionUtils.js
- client/apollo/js/Store/SeqFeature/Coverage.js
- client/apollo/js/Store/SeqFeature/SNPCoverage.js
- client/apollo/js/Store/SeqFeature/_MismatchesMixin.js
- client/apollo/js/View/Track/FeatureCoverage.js
- client/apollo/js/View/Track/SNPCoverage.js
@nathandunn This is ready for test and review.
To test, make sure the BAM track's store is `WebApollo/Store/SeqFeature/BAM` and the track type is `WebApollo/Track/SeqFeature/SNPCoverage` and `WebApollo/Track/SeqFeature/FeatureCoverage`.
For SNPCoverage, it would be best to try with a BAM which has reads with MD tag (not all BAMs have them).
Fixes #1826
> Add support for SNPCoverage and FeatureCoverage track types for projection

- docs/Configure.md
- grails-app/conf/Config.groovy
- grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
- grails-app/services/org/bbop/apollo/PreferenceService.groovy
This allows the native track list behavior to be true for new users.
> added selection of the default native track list behavior

- grails-app/services/org/bbop/apollo/CdsService.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
> prevents bad setting of translation start and end

- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/conf/BuildConfig.groovy
- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/bbop/apollo/TrackController.groovy
- grails-app/controllers/org/bbop/apollo/VcfController.groovy
- grails-app/services/org/bbop/apollo/TrackService.groovy
- grails-app/services/org/bbop/apollo/VcfService.groovy
- src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
- web-app/js/restapidoc/restapidoc.json
@nathandunn 
To get variant data as JSON,
- `localhost:8080/apollo/vcf/human/variants_track_name/1:15001..16000.json` should give you the variant and its information (by default the genotype is not included)
- `localhost:8080/apollo/vcf/human/variants_track_name/1:15001..16000.json&includeGenotypes=true` should give you the variant, its information and associated genotypes.
Let me know if you the JSON representation needs tweaking or if there is something missing.
> Add ability to fetch variant data from track via web services

- grails-app/services/org/bbop/apollo/PreferenceService.groovy
fix a bug on a corner case of web services: updateOrganismPermission will fail to update an organism permission due to looking up the organism in DB ignoring case. 
So if "orgam" and "Orgam" both exist, call updateOrganismPermission on orgam will actually updating the permission for Orgam.
> fix a bug on update Organism Permission

- docs/web_services/examples/groovy/Apollo1Operations.groovy
- docs/web_services/examples/groovy/migrate_annotations1to2.groovy
Hi,
I had to modify the script to migrate data from an old apollo 1 instance to a 2.1.0 instance. Here's the patch.
It mainly fixes some IllegalThreadStateException occuring randomly
It works, BUT, I see it doesn't migrate all the names, symbols, dbxrefs that people entered on the old server. Is there a way to migrate this data too? It is for ~700 genes, so people will not like entering it again
> Migration script fix (apollo1 -> apollo2)

- src/groovy/org/bbop/apollo/sequence/SequenceTranslationHandler.groovy
> fixed masking problem

- apollo
tweak jbrowse tools install: cpanm is installed with jbrowse, but
needs to be invoked with path to jbrowse bin directory; restrict
use of --notest to one problematic package (to avoid masking new
issues that may occur in future); install into specific 'exitlib'
directory; and echo a message advising adding the path to PERL5LIB
> fix for #201: tweak jbrowse tools install to fix CPAN package install

- grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- grails-app/domain/org/bbop/apollo/Organism.groovy
- grails-app/services/org/bbop/apollo/AnnotatorService.groovy
- src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
- src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
- src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
- src/gwt/org/bbop/apollo/gwt/client/dto/OrganismInfo.java
- src/gwt/org/bbop/apollo/gwt/client/dto/OrganismInfoConverter.java
- src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java
> initial commit of obsolete genomes

- client/apollo/js/View/Track/AnnotTrack.js
This PR fixes a bug that caused an infinite loop inside the `addToAnnotation` function.
The bug would present itself when multiple pieces of evidence were dragged together to adjust an existing annotation. The important change is on line 900 where a nested loop re-used the index value `i`, essentially:
```js
for(var i = 0; i < 10; ++i) {
// Code here is run an infinite number of times, 
// because i is constantly being reset to i=5 at the
// end of the inner loop. I blame JS scoping ;)
for(var i = 0; i < 5; ++i) {
// some other code
}
}
```
This PR also includes a fix for an ifelse branch on line 1047 that was unreachable, where the result of a call to `toUpperCase` was compared to "indel" rather than "INDEL". 
This PR also includes a couple of very minor linted fixes. Apologies if these …
> Bugfix multiple evidence

- grails-app/services/org/bbop/apollo/SequenceService.groovy
Just a little patch to support `JBrowse/Store/SeqFeature/IndexedFasta` storeClass as it's the old name of `JBrowse/Store/Sequence/IndexedFasta` and it's still used by prepare-refseqs.pl
> Compatibility with old name of indexedfasta storeclass

- client/apollo/js/main.js
A fix for a little problem I have when enabling the [quick bookmark](https://github.com/TAMU-CPT/bookmarks-jbrowse) jbrowse plugin in my apollo instance: the "Search Sequence" submenu in the "Tools" menu doesn't appear.
It seems like the problem is that the quick bookmarks plugin creates the menu, renders it, then a bit later (as the apollo plugin takes a little more time to load) the apollo adds an item to the menu, but as it's already rendered, it doesn't appear.
I have the feeling that `this.browser.renderGlobalMenu()` should take care of it, but I don't know how to call something like `dijitRegistry.byId()` from it... What do you think?
(should I target the develop branch instead of master?)
> Fix Search Sequence not displayed when Tools menu is already rendered

- client/apollo/js/main.js
Here's a little change to use the now-recommended-DraggableNeatHTMLFeatures track type instead of DraggableHTMLFeatures when uploading a GFF3 using the jbrowse upload box.
(Doing this as the DraggableHTMLFeatures has trouble displaying some of our gff files, while DraggableNeatHTMLFeatures display them perfectly)
> Use DraggableNeatHTMLFeatures type for gff3 uploaded from jbrowse

- client/apollo/css/webapollo_track_styles.css
- client/apollo/js/JSONUtils.js
- client/apollo/js/View/Track/AnnotTrack.js
- client/apollo/js/View/Track/SequenceTrack.js
- grails-app/conf/Config.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- src/gwt/org/bbop/apollo/gwt/client/dto/VariantPropertyInfo.java
> create an "add variant effect view" and a "remove variant effect view"

- docs/Setup.md
- grails-app/controllers/org/bbop/apollo/go/GoAnnotationController.groovy
- grails-app/domain/org/bbop/apollo/go/GoAnnotation.groovy
- grails-app/services/org/bbop/apollo/GpadHandlerService.groovy
- grails-app/services/org/bbop/apollo/SequenceService.groovy
- grails-app/services/org/bbop/apollo/go/GoAnnotationService.groovy
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfoConverter.java
- src/gwt/org/bbop/apollo/gwt/client/dto/GoAnnotationConverter.java
- src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkOntologyOracle.java
- src/gwt/org/bbop/apollo/gwt/shared/go/GoAnnotation.java
- src/gwt/org/bbop/apollo/gwt/shared/go/Reference.java
a major refactor for the go editing
> Fix 1134 go refactor v1

- grails-app/controllers/org/bbop/apollo/go/GoAnnotationController.groovy
- grails-app/domain/org/bbop/apollo/go/GoAnnotation.groovy
- grails-app/services/org/bbop/apollo/go/GoAnnotationService.groovy
- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
- src/gwt/org/bbop/apollo/gwt/client/dto/GoAnnotationConverter.java
- src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkOntologyOracle.java
- src/gwt/org/bbop/apollo/gwt/client/rest/GoRestService.java
- src/gwt/org/bbop/apollo/gwt/shared/go/Aspect.java
- src/gwt/org/bbop/apollo/gwt/shared/go/GoAnnotation.java
- web-app/js/restapidoc/restapidoc.json
fixes #2172 
- ~~based on aspect update to use other restrictions?~~
> Restrict ro fix 2172

- docs/web_services/examples/shell/addNames.sh
- grails-app/conf/BootStrap.groovy
- grails-app/conf/Config.groovy
- grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
- grails-app/controllers/org/bbop/apollo/SuggestedNameController.groovy
- grails-app/domain/org/bbop/apollo/SuggestedName.groovy
- grails-app/domain/org/bbop/apollo/SuggestedNameOrganismFilter.groovy
- grails-app/views/suggestedName/_form.gsp
- grails-app/views/suggestedName/create.gsp
- grails-app/views/suggestedName/edit.gsp
- grails-app/views/suggestedName/index.gsp
- grails-app/views/suggestedName/show.gsp
- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
- src/gwt/org/bbop/apollo/gwt/client/SuggestedNameOracle.java
- web-app/js/restapidoc/restapidoc.json
fixes #1991 
===
=== maybe not these ===
- ~~add integration test for controller?~~
- ~~get file upload working~~ would just use a psql upload for now
> Auto name fix 1991

- grails-app/controllers/org/bbop/apollo/TrackController.groovy
- grails-app/services/org/bbop/apollo/TrackService.groovy
> fixes subselection

- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- web-app/js/restapidoc/restapidoc.json
fixes #2293 #2294 #2295  and fixes https://github.com/galaxy-genome-annotation/python-apollo/pull/18
> handling web boolean flags properly

- .travis.yml
- ChangeLog.md
- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- test/config/mysql.travis
- test/config/postgres.travis
fixes #2285
I think this is a bad approach: https://travis-ci.org/GMOD/Apollo/builds/607248625
I think this might be a better approach https://docs.travis-ci.com/user/triggering-builds
@abretaud  / @erasche    What do you think about triggering python-apollo builds off of Apollo commits (at least ones to `develop` and `master`)?
> experiment to test if python-apollo integration will work

- .travis.yml
- test/config/python-apollo.travis
So we're getting closer to a working python-apollo testing
Is there a default user in the apollo launched in travis, or should I create it?
fixes #2285
> Finish python-apollo testing

- grails-app/services/org/bbop/apollo/SequenceSearchService.groovy
- src/groovy/org/bbop/apollo/sequence/search/blast/BlastAlignment.java
- src/groovy/org/bbop/apollo/sequence/search/blat/BlatCommandLine.java
- src/gwt/org/bbop/apollo/gwt/client/SearchPanel.java
fixes #2317 
was a bad blat configuration
```
Unable to perform search(TypeError) : Cannot read property 'isArray_3_g$' of null {"error":"No such property: eValue for class: org.bbop.apollo.sequence.search.blast.TabDelimittedAlignment\nPossible solutions: EValue"} 200
```
> fixed typo and added debugging

- docker-files/createenv.sh
- docker-files/launch.sh
While there is existing support for using a separate container/install of postgres when using docker, the postgres service inside the apollo container is started regardless.  This is what I image adding a flag to turn it off would look like.  You could argue that the if statement should cover all postgres setup, but I'll leave that to you - there is probably some value to leaving it there, in case you want your brand new external container to get the setup.
> make postgres start optional for Docker container

- .dockerignore
- .travis.yml
- Dockerfile
- docker-files/docker-apollo-config.groovy
- grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
- grails-app/controllers/org/bbop/apollo/OrganismController.groovy
- grails-app/domain/org/bbop/apollo/Sequence.groovy
- grails-app/services/org/bbop/apollo/SequenceService.groovy
fixes #2307 
Replaces my bad merge in #2310
> Fix 2307 v1

- .travis.yml
Using the master branch now that https://github.com/galaxy-genome-annotation/python-apollo/pull/22 is merged
> use master branch of python-apollo

- grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
- grails-app/domain/org/bbop/apollo/Feature.groovy
fixes #2235 
For transcript:
---
> fix transcript official transcript tracks for the remaining attributes

- Dockerfile
- docker-files/build.sh
- docker-files/launch.sh
This has been failing builds:
https://quay.io/repository/gmod/apollo?tab=builds
It looks like openjdk was already installed, so not sure why it was in there in the first place.
This seems to fix it.
> removed jdk8 from build

- src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/ProvenancePanel.java
- src/gwt/org/bbop/apollo/gwt/client/ProvenancePanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/go/GoEvidenceCode.java
- src/gwt/org/bbop/apollo/gwt/client/go/GoService.java
- src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkLookup.java
- src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkOntologyOracle.java
- src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkSuggestBox.java
> refactor for default ECO codes

- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
- src/gwt/org/bbop/apollo/gwt/client/AttributePanel.java
- src/gwt/org/bbop/apollo/gwt/client/CommentPanel.java
- src/gwt/org/bbop/apollo/gwt/client/DbXrefPanel.java
- src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
- src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
- src/gwt/org/bbop/apollo/gwt/client/ProvenancePanel.java
- src/gwt/org/bbop/apollo/gwt/client/RepeatRegionDetailPanel.java
- src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
- src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
fixes #2431 
Should reflect change here: 
https://github.com/GMOD/Apollo/commit/4c09bfac53de025102412c55bcbabaedf1ec6a52
---
> fixing UI for permissions

- grails-app/services/org/bbop/apollo/FileService.groovy
A little bug fix for creating/updating an organism in remote mode: when extracting symlinks, we need to make sure the parent dir exists as is done for non-symlink files
Tested and approved on bipaa.genouest.org/apollo/ :)
> tar.gz extraction: make sure parent directory exists

- Dockerfile
I kept getting an error on building the docker image for Apollo at the `pip3 install nose apollo==4.2.4` stage. 
From Quay.io build log:
```
RUN pip3 install nose apollo==4.2.4
7/27/2020, 8:12:47 PM
7/27/2020, 8:12:47 PM---> Running in 463b33386a8e
7/27/2020, 8:12:48 PMCollecting nose
7/27/2020, 8:12:48 PMDownloading https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl (154kB)
7/27/2020, 8:12:48 PMCollecting apollo==4.2.4
7/27/2020, 8:12:48 PMDownloading https://files.pythonhosted.org/packages/4d/74/4c1488902216ba732cd18a816fb06e8200596ff63f8c98e3deb1e26f00a3/apollo-4.2.4.tar.gz (42kB)
7/27/2020, 8:12:48 PMComplete output from command python setup.py egg_info:
7/27/2020, 8:12:48 PMTraceback (most recent call …
```
> Fixes Docker Image Build Failure: "UnicodeDecodeError" on pip3 apollo install

- src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.java
- src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/GoPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/ProvenancePanel.ui.xml
> fixes link and adds info boxes

- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
A fix for a bug I found on 2.6.2: for some of my genes, the attributes were not displayed in the annotation panel.
It turns out the list of attributes returned by getattributes contained some entries with no tag defined. In particular, Status which were defined for theses genes.
> Fix empty attribute list in annotation panel

- Dockerfile
- apollo
- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- grails-app/controllers/org/bbop/apollo/LoginController.groovy
Note - method for work:
Note: react client code is here: https://github.com/nathandunn/apollo-websocket-test 
Login from React:
- in client code, `yarn build` -> `cp build <apollo-src>/web-app/<target_dir>` assuming target_dir does not exist
- running apollo2  go to the react code (I don't even think this PR is necessary) go to `<apollo2_url>/<target_dir>`
- fill out proper username and password
- hit `Ajax Login`
- hit `WebSocket Login` (establishes the connection), can probably done on the callback
- Note that `get Current user` should work as well as the other methods
- Confirm that on `<apollo2_url>/<target_dir>` (via a refresh) that you will also be logged in
Logout from Logout:
- in client code, `yarn build` -> `cp build <apollo-src>/web-app/<target_dir>` assuming target_dir does …
> added routes to explore web socket security

- ChangeLog.md
- client/apollo/js/View/Track/AnnotTrack.js
- grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
- grails-app/services/org/bbop/apollo/FeatureService.groovy
- grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
- web-app/js/restapidoc/restapidoc.json
> fixes #2129

- client/apollo/js/TrackConfigTransformer.js
In recent version of Apollo, BlastView tracks (https://github.com/TAMU-CPT/blastview/) are broken: there's no contextual menu entry to "create new annotation" (and no drag and drop as it's a canvas track).
This patch fixes it
> Fix contextual menu for blastview tracks

- Dockerfile
This makes the Python libraries (including the `arrow` cli tool) installed globally in the Docker image. Before this they were installed under the `apollo` user, and then subsequently deleted by build.sh.
Fixes #2620
> Make Python libraries installed globally in Docker image

- Dockerfile
Hi GMOD,
As per an earlier discussion on the Apollo mailing list, I've tested a new version of the Apollo Docker build with an Ubuntu base image update from 18.04 -> 20.04.
The change addresses three vulnerabilities (one critical) by updating Tomcat from 9.0.16 (Ubuntu 18.04) to 9.0.31 (Ubuntu 20.04). The vulnerable version of Tomcat was detected by our campus sysadmins and we were not permitted to run the Apollo Docker image until they were patched.
I haven't found any significant differences in the build logs from 18.04 versus 20.04 (both attached) and I have 20.04 working locally without any issues --is there any additional testing on your end that needs to happen before considering an update of the Dockerfile?
If there's any other information or assistance I can provide, please let me …
> Updated Dockerfile to use Ubuntu 20.04 as the base image. Vulnerability fixes.

- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.ui.xml
In an email from a user, they stated:
> ...we have noticed a problem with the ‘Partial’ field in the Apollo annotation editor that manifests when a gff file is created for a gene model.
>
> The current UI stores the value of 3' as fmin_partial, and 5' as fmax_partial, which is incorrect, it should be the opposite. Also fmin_partial and fmax_partial are relative to the reference sequence, not the feature on its strand which might be what the annotator expects (so its ambiguous).
From what I can tell, the "partial" feature in Apollo is based on a similar feature in Artemis, see [here](https://github.com/GMOD/Apollo/issues/2565). Artemis appears to use 5' and 3' relative to the feature on the strand, though, and Apollo does not, so I think all the above observations are correct.
After …
> Use fmin and fmax for partial instead of 3' and 5'

- src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
- src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.ui.xml
Fixes #2648 by adding a tooltip that describes what "fmin" and "fmax" are in the context of "Partial"
The text reads: "Indicates that the end of a gene is partial. "fmin" is the 5' end, and "fmax" is the 3' end (relative to the reference sequence, not the feature strand)."
Here is a screenshot:
> Add info icon with tooltip describing meaning of fmin and fmax in "Partial"

- .github/workflows/python-apollo.yml
- grails-app/conf/BuildConfig.groovy
- grails-app/views/annotator/instructorReport.gsp
this is a possible method to remove log4j jars from the resulting build
I ran 
```
./apollo deploy
cd target
mkdir output
cp apollo-2.6.7-SNAPSHOT.war output/apollo.zip
cd output
unzip apollo.zip
find .|grep log4j
```
output
```
WEB-INF/lib/log4j-1.2-api-2.19.0.jar
WEB-INF/lib/log4j-api-2.19.0.jar
WEB-INF/lib/log4j-core-2.19.0.jar
WEB-INF/lib/tomcat-embed-logging-log4j-7.0.70.jar
```
these are up to date versions of log4j v2
I then deployed this war file and it did not crash on startup
> Update to log4j 2.19.0

- .github/workflows/python-apollo.yml
- grails-app/controllers/org/bbop/apollo/UserController.groovy
- grails-app/services/org/bbop/apollo/PermissionService.groovy
- grails-app/services/org/bbop/apollo/PreferenceService.groovy
> Fix ability to see/add users in UI when there are not yet any organisms

- Dockerfile
The latest builds of `blat` and `faToTwoBit` need at least v2.33 of glibc, but the ubuntu base image has v2.31. This downloads an older build instead that works on the image.
Fixes #2668
> Bugfix: blat not working in Docker build
