src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.ui.xml

initial pull request from 2.0 into master

Apollo2 init pull request

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/domain/org/bbop/apollo/FeatureEvent.groovy
grails-app/services/org/bbop/apollo/FeatureEventService.groovy
test/unit/org/bbop/apollo/FeatureEventServiceSpec.groovy

#356 - improved the current functionality when undoing and redoing history

History tree

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

@deepakunni3  Can you review this and go ahead and pull it in if you think it looks like it fixes #468 (it looks like it does).

Set orf changes

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/LoginController.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/dto/UserInfo.java

meant to fix #480 . . . 
@cmdcolin 
Can you review, test and merge this, this week when you have a chance this week. 
Let me know if there are any issues for me to fix with it.  Thanks.

Force logout over websockets 

---

ChangeLog.md

I just wanted to update the changelog a little bit to...
- make formatting consistent
- add missing things
- divide features from RC1,RC2,RC3

Cleanup Changelog

---

client/apollo/js/TrackConfigTransformer.js
client/apollo/js/View/Track/WebApolloCanvasFeatures.js

This option adds a right-click option to create a new annotations based on a CanvasFeatures track
See #437 for background

Add "Create new annotation" right-click menu to the CanvasFeatures tracks

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/bbop/apollo/GroupController.groovy
src/gwt/org/bbop/apollo/gwt/Annotator.gwt.xml
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/UserPanel.java
src/gwt/org/bbop/apollo/gwt/client/UserPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/dto/UserInfo.java
src/gwt/org/bbop/apollo/gwt/client/event/GroupChangeEvent.java
src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

This is for #592  . . 
@deepakunni3   Can you merge this in if it looks good.   There are a few places I used the "alerts", so you might need to fix those (I wasn't sure what your final solution was for it).

Redo group user ui

---

apollo
docs/Configure.md
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/GroupController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
restapidoc.json

Add logging

---

src/gwt/org/bbop/apollo/gwt/client/LoginDialog.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

Login error dialog fixed

---

src/gwt/org/bbop/apollo/gwt/client/LoginDialog.java
src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml

This just cleans up the login a little bit
The logins and alerts were updated with the bootstrap theme recently but I made it look slightly more compact
Before this PR
After

Uibinder login

---

grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/domain/org/bbop/apollo/UserOrganismPreference.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

This adds a checkbox to the track panel to enable the native track list view
The page is then refreshed and it will render the native jbrowse track selector
The toggle is stored in the UserOrganismPreference table
See #597

Trackpanel native

---

src/gwt/org/bbop/apollo/gwt/client/LoginDialog.java
src/gwt/org/bbop/apollo/gwt/client/LoginDialog.ui.xml

This fixes several of the comments from #609 
- uses better bootstrap layout styles (no flowpanels)
- has error icon
- has padding
- add a link to the public jbrowse

Uibinder login2

---

client/apollo/js/main.js

This is a pretty simple fix.  My "idea" would be to replace the "full-screen" view with an annotator view.  In the interim I think that this is good.  @cmdcolin If you want to review / fix this, that would be great. 
Thanks.

#626 - login from public genomes . . added to annotation view

---

ChangeLog.md
docs/Architecture.md
docs/Data_loading.md
docs/Troubleshooting.md
docs/web_services/examples/groovy/add_organism.groovy
docs/web_services/examples/groovy/add_users.groovy
docs/web_services/examples/groovy/alter_group_permissions.groovy
docs/web_services/examples/groovy/alter_user_groups_and_permissions.groovy
docs/web_services/examples/groovy/delete_annotations_from_organism.groovy
docs/web_services/examples/groovy/get_gff3.groovy
docs/web_services/examples/groovy/get_usersinwa1.groovy
docs/web_services/examples/groovy/migrate_annotations1to2.groovy
docs/web_services/examples/groovy/stress_test.groovy
docs/web_services/examples/groovy/transfer_annotations2to2.groovy
docs/web_services/examples/perl/test_add_feature.pl
docs/web_services/examples/perl/test_remove_features.pl
scripts/print_all_features.sh
tools/data/add_transcripts_from_gff3_to_annotations.pl

Closes #638.  
@cmdcolin   Could you review and merge this?  
@monicacecilia  You can take a look at these as well, but I think these are the correct changes.

Rebrand WebApollo2 to Apollo

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

@cmdcolin   Could you review this on Monday and pull it in.    Thanks!

Annotator controller and REST services and check security  - #649

---

grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/views/featureEvent/changes.gsp

See #642 
This adds a "simpler" recent changes page
The pre-existing recent changes had odd behavior and broken sorting mechanisms
This one uses a custom criteria query to add flexible and accurate sorting on even deeply nested attributes

Update recent changes

---

grails-app/controllers/org/bbop/apollo/LoginController.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/RegisterDialog.java
src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

Silent fail register admin error handling fix - #658
Just lets you know that there is an error.  No fancy bootstrap stuff yet, but at least a user will be less confused potentially.

Silent fail register admin error handling fix - #658

---

grails-app/conf/BootStrap.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/TrackController.groovy
grails-app/domain/org/bbop/apollo/Bookmark.groovy
grails-app/services/org/bbop/apollo/BookmarkService.groovy
grails-app/services/org/bbop/apollo/FeatureProjectionService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/ProjectionService.groovy
src/groovy/org/bbop/apollo/projection/ProjectionDescription.groovy
src/gwt/org/bbop/apollo/gwt/client/dto/bookmark/BookmarkInfoConverter.java
test/unit/org/bbop/apollo/MultiSequenceProjectionSpec.groovy

Just an FYI @deepakunni3   and @cmdcolin   I changed a few small things so you might need to reload the DB.  I'm going to merge and probably to most of the rest of the work into master until things stabilize.

Fix annotations

---

grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/services/org/bbop/apollo/ProjectionService.groovy
grails-app/services/org/bbop/apollo/TrackService.groovy
src/groovy/org/bbop/apollo/projection/TrackIndex.groovy
test/integration/org/bbop/apollo/TrackServiceIntegrationSpec.groovy

Need review on the changes made and they way HTTP Status 404 is returned by JbrowseController when projected ncList array is empty.

Pull request for fixing #707 - remove JSONArray outside of projection (things that return -1)

---

grails-app/services/org/bbop/apollo/TrackService.groovy
test/integration/org/bbop/apollo/FeatureProjectionServiceIntegrationSpec.groovy
test/integration/org/bbop/apollo/TrackServiceIntegrationSpec.groovy

Remove original offset

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy

fix_annotations

---

client/apollo/css/add_sequence_alteration.css
client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/SequenceTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

This PR allows users to add comments while creating sequence alteration.
Thanks to @NehaVC for her inputs, ideas and feedback.
See #781 for more details on this feature request.

Adding comments to sequence alterations

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfo.java
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfoConverter.java

This PR extends the way we query the server and populate dataGrid in AnnotatorPanel to include 'Date of Last Updated' and let users sort annotations by date.
See #770

Ability to sort annotations by their 'last updated' in Annotator Panel

---

client/apollo/js/main.js

Add a fix for strand filtering

---

apollo
grails-app/controllers/org/bbop/apollo/GroupController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

Small fixes for #771 and #767

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

Fix the bug in this case where the delete event should be changed to an update https://github.com/GMOD/Apollo/issues/764

Send an update operation when an attribute is removed

---

client/apollo/css/get_history.css
client/apollo/js/View/Track/AnnotTrack.js

Made changes to history box - related to #797
Just minor cosmetic changes.

Made changes to history box - related to #797

---

grails-app/conf/Config.groovy
grails-app/migrations/changelog-2.0.1.groovy
grails-app/migrations/changelog.groovy

Fix for #794  . . . was not updating mysql databases correctly.

#815 - removing schema fixes for mysql migration #794

---

src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

#625 - pushing to test on staging

---

docs/Command_line.md
docs/web_services/examples/groovy/get_gff3.groovy
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy

Reverts GMOD/Apollo#830
Crap . . exporting ALL I get:
```
| Error 2016-01-29 11:50:52,899 [http-bio-8080-exec-8] ERROR errors.GrailsExceptionResolver  - QueryException occurred when processing request: [POST] /apollo/sequence/getSequences/ - parameters:
sort: count
asc: true
start: 0
name: 
length: 20
could not resolve property: count of: org.bbop.apollo.Sequence. Stacktrace follows:
Message: could not resolve property: count of: org.bbop.apollo.Sequence
Line | Method
->>  102 | doCall            in org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    178 | $tt__getSequences in org.bbop.apollo.SequenceController
|    198 | doFilter . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
| …
```

Revert "Optimize GFF3 exports"

---

docs/Command_line.md
docs/web_services/examples/groovy/get_gff3.groovy
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy

@nathandunn 
Thanks for catching the last bug in #830
This adds a check for pseudogenes and other top level features

Optimize GFF3 redo (with pseudogene fix)

---

grails-app/controllers/org/bbop/apollo/SequenceController.groovy

Fixes comment in #838  about sequence search by name
Edit: refer to corrected issue number

Address sequence search in #838

---

ChangeLog.md

@cmdcolin @nathandunn Review needed

Update changeLog for release 2.0.2

---

grails-app/domain/org/bbop/apollo/Analysis.groovy
grails-app/domain/org/bbop/apollo/AnalysisFeature.groovy
grails-app/domain/org/bbop/apollo/AnalysisProperty.groovy
grails-app/domain/org/bbop/apollo/CVTerm.groovy
grails-app/domain/org/bbop/apollo/CVTermPath.groovy
grails-app/domain/org/bbop/apollo/CVTermRelationship.groovy
grails-app/domain/org/bbop/apollo/DB.groovy
grails-app/domain/org/bbop/apollo/DBXref.groovy
grails-app/domain/org/bbop/apollo/DBXrefProperty.groovy
grails-app/domain/org/bbop/apollo/Environment.groovy
grails-app/domain/org/bbop/apollo/EnvironmentCVTerm.groovy
grails-app/domain/org/bbop/apollo/Feature.groovy
grails-app/domain/org/bbop/apollo/FeatureCVTerm.groovy
grails-app/domain/org/bbop/apollo/FeatureGenotype.groovy
grails-app/domain/org/bbop/apollo/FeatureLocation.groovy
grails-app/domain/org/bbop/apollo/FeatureProperty.groovy
grails-app/domain/org/bbop/apollo/FeatureRelationship.groovy
grails-app/domain/org/bbop/apollo/FeatureSynonym.groovy
grails-app/domain/org/bbop/apollo/Genotype.groovy
grails-app/domain/org/bbop/apollo/OrganismDBXref.groovy
grails-app/domain/org/bbop/apollo/OrganismProperty.groovy
grails-app/domain/org/bbop/apollo/Phenotype.groovy
grails-app/domain/org/bbop/apollo/PhenotypeDescription.groovy
grails-app/domain/org/bbop/apollo/PhenotypeStatement.groovy
grails-app/domain/org/bbop/apollo/Publication.groovy
grails-app/domain/org/bbop/apollo/PublicationAuthor.groovy
grails-app/domain/org/bbop/apollo/PublicationDBXref.groovy
grails-app/domain/org/bbop/apollo/PublicationRelationship.groovy
grails-app/domain/org/bbop/apollo/Synonym.groovy

Fixes #881  . . . bad equality is a mine-field waiting to be explored.  
@cmdcolin   Can you take a quick look at this to double-check.   Surprised that this is the only way we've see this show up.

fixes #881 - use correct is statement

---

grails-app/views/home/systemInfo.gsp

Hide environment variables containing "password"

---

src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/dto/TrackInfo.java

fixes track scroll issue in #898

fixed track scroll issue

---

client/apollo/css/maker_styles.css
client/apollo/js/main.js
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java

Fix trackpanel deselection

---

grails-app/services/org/bbop/apollo/ExonService.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

This PR addresses the bug mentioned in #910.
It also includes integration tests to account for such use-cases.

Issue910 - improper CDS sequence export as a result of a sequence alteration with an in-frame stop codon 

---

apollo

@cmdcolin   Coud you take a look when you have a minute.  Thanks.

fixes case where nodejs exists, but node is not

---

docs/Configure.md
docs/ExampleBuild.md
docs/index.rst

I added an example build and a link to the JBrowse FAQ.   Let me know what you think or if you have any additions / suggestions.  I don't want to much doc to maintain, but I think that providing something like this might be helpful, esp. for folks not used to sysadmining their own systems.  If you think its overkill, let me know.
FYI @cmdcolin  @deepakunni3  @monicacecilia

updated documentation a bit

---

grails-app/domain/org/bbop/apollo/UserOrganismPermission.groovy
grails-app/services/org/bbop/apollo/ReportService.groovy
grails-app/taglib/org/bbop/apollo/PermissionTagLib.groovy
grails-app/views/annotator/report.gsp

updated report to include more permissions on the [annotator report page](http://localhost:8080/apollo/annotator/report/):

added permissions for each user

---

grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/domain/org/bbop/apollo/User.groovy
restapidoc.json
src/gwt/org/bbop/apollo/gwt/client/MutableBoolean.java
src/gwt/org/bbop/apollo/gwt/client/UserPanel.java
web-app/js/restapidoc/restapidoc.json

added a simpler user model change 

---

apollo

just added an additional target "run-app" so that we don't have to compile gwtc each time

added apollo run-app

---

grails-app/views/annotator/index.gsp
src/gwt/org/bbop/apollo/gwt/client/Annotator.java

You should just be able to edit the index.gsp now.     Can be over-written with plugins etc., later, but sufficient for modification out of a build.

added ability to add a header and footer

---

sample-docker-apollo-config.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy

Tangential: what's the rationale for defaulting to NeatCanvas/NeatHTML? One of my tracks doesn't play nicely with it (bug report soon) and it's aesthetically a step backwards from the original Canvas/HTML (at least in our use case).

Update config files for new plugin system

---

grails-app/conf/Config.groovy
grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/controllers/org/bbop/apollo/HomeController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/views/auth/login.gsp
grails-app/views/layouts/login.gsp

Fixes #809. 
there is a better fix using the natural shiro api's, but SecurityFilter kind of messes that up a bit.  Anyway, what is here is good enough and provides the login. 
Nathan

added the login for non-annotator pages

---

grails-app/conf/Config.groovy
grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/controllers/org/bbop/apollo/HomeController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/views/auth/login.gsp
grails-app/views/layouts/login.gsp

@cmdcolin   Could you take a look at this on Monday.  
It should fix #532.  
It fixes it as I would expect ..  setting the property properly inbetween the intron.

Fix setting translation startend intron

---

grails-app/conf/Config.groovy
grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/controllers/org/bbop/apollo/HomeController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/views/auth/login.gsp
grails-app/views/layouts/login.gsp
src/gwt/org/bbop/apollo/gwt/client/resources/Table.css

Fixed #632 . . . 
Highlight is still allowed using keyboard or hover, but they are always readable (black text).  
@deepakunni3   Can you review this on Monday?

Hover gwt colors

---

build.gradle

When deploying with run-local Apollo was actually switching to the master branch (yikes). 
FYI @deepakunni3  and @cmdcolin   
Was this what you were talking about @deepakunni3 ??

updated so that not switching to master branch

---

.travis.yml
grails-app/conf/BootStrap.groovy
test/config/mysql.cnf
test/config/mysql.travis
test/config/postgres.travis
test/integration/org/bbop/apollo/ChadoHandlerServiceIntegrationSpec.groovy
test/integration/org/bbop/apollo/Gff3HandlerServiceIntegrationSpec.groovy

Try it again .  Related to the fix on #983 and my botched attempt of #984 .

Cmdcolin fix travis database tests

---

.travis.yml
docs/ChadoExport.md
docs/index.rst
sample-postgres-apollo-config.groovy

Addresses the requirements specified in #992.

Chado export configuration (do not merge)

---

docs/Troubleshooting.md

This should close #1020 as we had insufficient instructions.

add directions of accessing git behind a firewall

---

apollo
build.gradle

Should fix #1020.  @cmdcolin  Could you review.

Fix jbrowse local install

---

grails-app/conf/UrlMappings.groovy

@deepakunni3   Can you review when have a chance? 
I opened it up for the proxy to work whether or not there was a client token provided.

fix #1028 . . proxy requests need to support client token

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/domain/org/bbop/apollo/Preference.groovy

Fix missing client token

---

apollo
build.gradle
grails-app/conf/Config.groovy

@deepakunni3  Can you take a look at this when you have a chance?  I cleaned some stuff up, but mostly I made sure that you could successfully do a clone and then run ```./apollo run-local``` and have it install JBRowse successfully.
No rush.  
Thanks.

fixed build when run-local is the first command

---

build.gradle
docs/Configure.md
grails-app/conf/BootStrap.groovy
grails-app/controllers/org/bbop/apollo/LoginController.groovy
grails-app/services/org/bbop/apollo/UserService.groovy
sample-docker-apollo-config.groovy

Fixes #1040  Adds an admin user on startup. 
@erasche   Let me know if this one works for you.

1040 add user on startup

---

grails-app/migrations/changelog-2_0_3.groovy

Fix changelog for H2 and change the id of changeset

---

docs/web_services/examples/shell/exportFeatures.sh
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/migrations/changelog-2_0_3.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

@erasche  and @deepakunni3   I think that this fixes the export file problems.    exportAllSequences was being ignored if set to true except for Chado.   
Let me know what you think.

 #1045 - cleaned up API description and doc

---

apollo
build.gradle
build.xml

Fixes https://github.com/GMOD/docker-apollo/issues/1

cleaned up build scripts so that ant is not calling gradle

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy

@deepakunni3   This should fix the blat search error.   Can you double-check.   Thanks.

1054 fix blat search

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy

Should fix all of the issues with brought up in #1055. 
@deepakunni3  Can you check that this works.  
Thanks.

fixed issues to do with invalid path

---

grails-app/services/org/bbop/apollo/FastaHandlerService.groovy

Prevent export of FASTA headers when sequence is empty

---

src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.ui.xml

This PR addresses the requests made in #730

Add an easy way to show selected sequences and clear selection on the Sequence Panel

---

src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

@deepakunni3  Can you check that this is working / makes sense?    Should allow remembering the last tab you were on.

should remember the last tab it was on

---

src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.ui.xml

Fix export UI in Sequence Panel

---

src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.ui.xml

fixes the dropup issue in #1066
@deepakunni3  can you review?  
They have this fix in the master branch of gwt-bootstrap-extras (you can just do a select.setDropupAuto(false)) . . and this does the same thing.

fixed the user-group dropup problem 1066

---

client/apollo/js/View/Track/WebApolloCanvasFeatures.js

Fix method call for pseudogene, repeat_region and transposable_element on CanvasFeatures

---

client/apollo/js/View/Track/AnnotTrack.js

Fix owner display while hovering over a feature

---

application.properties
client/apollo/js/View/Track/AnnotTrack.js
grails-app/conf/BuildConfig.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy

Fixes the rest of #1085 . . 
@deepakunni3  Can you take a look at this when you hav ea chance.  It will probably be our RC2.

Deepakunni3 issue 1085

---

client/apollo/js/View/Track/AnnotTrack.js

- Updated text for Tooltips for "Name", "DBXRefs", "PubMed IDs" fields. 
- Also updated label for "PubMed IDs" table.

Updated text Info Editor Tooltips and labels.

---

grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

@nathandunn 
- Fixes the issue I found with `addFeature()` in `FeatureService`.
- Fixes the naming of non-coding features to be more sensible.

Fix add feature and naming scheme

---

docs/web_services/examples/groovy/delete_annotations_from_organism.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/domain/org/bbop/apollo/UserOrganismPreference.groovy
grails-app/services/org/bbop/apollo/AnnotatorService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/PreferenceService.groovy
src/gwt/org/bbop/apollo/gwt/client/Annotator.java

Fixed issues with last remembered and simplifies the code base a bit.  Also handles the case where store is not set.

1102 fix scaffold

---

client/apollo/js/main.js
grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy

Should be a fix for the following:
#1110 and #1108 and #1107

Fix raw reads

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/main.js
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/services/org/bbop/apollo/SequenceSearchService.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java

This pull request address a number of issues. 
#1112 , #1113 ,  #1115 , #1116
Some issues will need to be retested:
#1107 , #1110 , #1114

Slider fix

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/json/annot.json
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

Switch organism correctly

---

client/apollo/js/View/Dialog/Help.js

Updated User Guide URL

---

docs/web_services/examples/groovy/Apollo1Operations.groovy

Updates Apollo1Operations.groovy to include the driver for Postgres 9.4

added  new driver for Postgres 9.4 in Apollo1Operations.groovy

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy

this will handle #1147  . . . went from 1.5 seconds for a large set of exons to 47 ms

sped up features by not creating full JSON

---

grails-app/services/org/bbop/apollo/PreferenceService.groovy

@deepakunni3  This should fix this.
Fixes #1150

fixes empty database problem

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
src/gwt/org/bbop/apollo/gwt/client/Annotator.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

This is related #493  . . . basically it checks if the session times out every minute and asks you if you want to reconnect. 
FYI @monicacecilia   Hopefully this is the right solution.  
@deepakunni3  Can you check when you have time.   Sessions probably won't timeout (since its keeping them alive).

Keep session alive

---

docs/web_services/examples/groovy/SampleFeatures.groovy
docs/web_services/examples/groovy/stress_test.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy

This handles #1155 . . Should fix the web services problems.

Fix webservices 1155

---

client/apollo/js/main.js
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy

This will handle #1156. 
@childers Can you review this one?

Fix for 1156

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

@deepakunni3  Can you review this when you have a chance?   Should handle #1163.

fixed removal of DbXrefs

---

client/apollo/js/View/Track/SequenceTrack.js

Fix bug in JSON while handling comment for sequence alterations

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/services/org/bbop/apollo/FastaHandlerService.groovy

Want @monicacecilia  review on #1152 before I have this reviewed / merged

Fix export highlighted sequence 1152

---

tools/data/add_transcripts_from_gff3_to_annotations.pl

This simply fixes some confusions in the bulk loading script.

Fix argument definition and parameters in add_transcripts_from_gff3_to_annotations.pl to avoid ambiguity

---

client/apollo/js/View/Track/DraggableHTMLFeatures.js
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/services/org/bbop/apollo/FastaHandlerService.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

Handles case 1152.
@deepakunni3  Can you take a look at this and verify that it seems to solve at least [these two cases](https://github.com/GMOD/Apollo/issues/1152#issuecomment-235900703)?

Fix genomic export from highlighted region 1152

---

docs/TestScript.md

updated testing script for 2.0.4
@monicacecilia  Can you review these changes.  Wasn't sure 7.1.8 (should it be removed, or just clarified), but other than that, I hope the other changes more or less make sense.

modified testing script for Apollo 2.0.4-RC3

---

client/apollo/js/main.js
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/controllers/org/bbop/apollo/LoginController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/PreferenceService.groovy
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/UserPanel.java

Handles #1195.   
@deepakunni3  Can you review this when you have a moment.  Thanks.

Fix full screen 1195

---

grails-app/controllers/org/bbop/apollo/UserController.groovy

#1230 - fixed

---

grails-app/controllers/org/bbop/apollo/GroupController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

@childers   Does this look right for fixing #1244 ?

updated REST API doc

---

src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.ui.xml

this should fix #1242  .  .  . I'll lave adding search as an exercise for the user.

added pagination to group panel list

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/AuthController.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy

should handle the specific case brought up in #1214

---

grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/NameService.groovy
grails-app/services/org/bbop/apollo/OverlapperService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
scripts/delete_only_features.sh
src/groovy/org/bbop/apollo/FeaturePositionComparator.groovy

@deepakunni3  Can you confirm that this isn't breaking everything and it seems reasonable when you have a chance? 
Should fix #1276.  If you have any further thoughts that would be great as well.
Hopefully we'll get some further insight into user pain from @monicacecilia .

Optimization tests 1276

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

Fixes bug reported in  #1297 
Also added a simple integration test to check the CDS when a transcript, with an incomplete CDS, is added.
@nathandunn Ready for testing and review.

Issue 1297

---

docs/web_services/examples/groovy/get_new_features.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

Supports #1315 by adding a findChanges method.

Adds a findChanges method

---

docs/web_services/examples/groovy/get_new_features.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
restapidoc.json
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
web-app/js/restapidoc/restapidoc.json

Fixed chado admin - should fix #1322
@deepakunni3  Can you check this when you have a chance?

Fixed chado admin - should fix #1322

---

docs/Configure.md
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/public/theme.css

This PR closes #1332.  
Features

Config panel options 1332 v2

---

grails-app/services/org/bbop/apollo/PermissionService.groovy

returns JSON on error instead of false  FYI @erasche on #1275.
@deepakunni3  This is ready to review when you have time.

fixed #1275

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/main.js
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
src/gwt/org/bbop/apollo/gwt/client/LoadingDialog.java
src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

fixes #1277.  
Now there is only a single preference names "ignore" . .  a better solution might be not not write a preference to begin with.   But when testing a script it seems to work fine. 
Feel free to kick it back @deepakunni3

closes #1277, closes #1173, closes #1008, closes #1331

---

grails-app/views/login/doLogin.gsp

Fix login bootstrap 1103

---

grails-app/controllers/org/bbop/apollo/JbrowseController.groovy

closes #861 now only allowing views when public

---

grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/views/featureEvent/report.gsp
grails-app/views/layouts/_reportHeader.gsp

Changes page 806

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml

closes #1359

---

docs/CannedElements.md

Documentation about canned elements.

Documentation for Canned Elements. Resolves #1194

---

docs/Configure.md

Update details about canned comments, tags (keys), and values.

Canned Elements info

---

grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/AuthController.groovy

Used Shiro WebRequest  to simplify this code.

fixes #1371

---

grails-app/controllers/org/bbop/apollo/NcbiProxyServiceController.groovy

Update https request for NCBI - fixes #1377

---

docs/TestScript.md
grails-app/services/org/bbop/apollo/ExonService.groovy

@deepakunni3   I think this fixes it.   Was just starting at the wrong coordinates.

Fixes #1379 upstream donor

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java

Fixes #1385
@nathandunn Ready for review. Let me know if there is a better way to implement the missing behavior.

Fix double-click behavior for non-transcript features in AnnotatorPanel

---

grails-app/services/org/bbop/apollo/PermissionService.groovy

I think this should fix #1388.   FYI, @deepakunni3  / @childers .  Basically, shows a debug instead of throwing an error.

this should fix #1388

---

grails-app/services/org/bbop/apollo/PreferenceService.groovy

@mpoelchau, @childers   This should fix #1391.   I'll merge it into master and you can let me know.

fixes #1391

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/main.js
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.ui.xml

fix #1395 added a little navicon that will eventually show the button note - not ready to merge

---

ChangeLog.md
grails-app/conf/BootStrap.groovy
grails-app/services/org/bbop/apollo/PhoneHomeService.groovy

Fixes issue when starting up in devmode.

phonehome async Fixes #1419

---

client/apollo/css/webapollo_track_styles.css
client/apollo/js/View/Track/DraggableHTMLFeatures.js
client/apollo/json/annot.json
grails-app/conf/Config.groovy

Fix #1417 - fixes neat features showing up for single exon features

---

client/apollo/js/View/Track/AnnotTrack.js

fixes #1426

---

docs/Release.md
docs/TestScript.md

Clarifications of TestScript from #1435. 
@monicacecilia  Make sure I'm using Reference Sequence versus scaffold correctly.  Does our Reference Sequence panel hold a list of scaffolds or Reference Sequences?

fixes #1435

---

docs/TestScript.md
src/gwt/org/bbop/apollo/gwt/Annotator.gwt.xml
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.ui.xml

fixes #1452 
@deepakunni3  Can you review this?

added toggle switch and synced: fixes #1452

---

ChangeLog.md
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java

Double click fails.  Fixes #1459

---

grails-app/services/org/bbop/apollo/FeatureService.groovy

Avoids using feature 'type' when generating name for a feature.

Fixes #1451

---

ChangeLog.md
grails-app/services/org/bbop/apollo/FeatureService.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

Fixes a bug which was observed while resolving #1451 

Fix issue with gene names when performing undo and redo right after changing annotation type

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml

Fixes #1467
@deepakunni3  This is ready for you to review.

Fix doubleclick behavior Fixes #1467

---

grails-app/conf/Config.groovy

Added comment on use of NeatFeatures plugins in combination with Apollo

Added caution text

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js

Fixes #1465 
@nathandunn Ready for review and test.

Disable opening of annot_context_menu when selection is null

---

ChangeLog.md
grails-app/conf/Config.groovy
grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/authenticator/AuthenticatorService.groovy
grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy
grails-app/services/org/bbop/apollo/authenticator/UsernamePasswordAuthenticatorService.groovy

initial fix #1468
@abretaud  This PR should fix it.  Let me know if not.  
@deepakunni3  If you could take a look and let me know if I didn't destroy anything.  Thanks!

initial fix #1468

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

@deepakunni3  I think this fixes the small problem with the sticky tracks from loadLinks.

Fix load link

---

grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
tools/data/add_transcripts_from_gff3_to_annotations.pl

Fix for issue 1475 - NAL test

---

docs/Configure.md
docs/Migration.md
docs/Prerequisites.md
docs/Setup.md

@deepakunni3  Can you review these to make sure it makes sense? 
Thanks!

made some minor changes to the doc

---

docs/web_services/examples/groovy/add_users.groovy
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

Fix user role add fixes #1509

---

client/apollo/js/View/Track/AnnotTrack.js
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java

Using postmessage for integration with the iFrame:
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
This has a significant advantage in that I don't have to keep functions registered in the parent, or register them at all. 
We do check host and have a custom function, so I think that addresses the major security concerns.  
I also removed some of the customGwt as done in #1522.

use postMessage for integration

---

docs/Data_loading.md
docs/TestScript.md
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
tools/data/add_features_from_gff3_to_annotations.pl
tools/data/add_transcripts_from_gff3_to_annotations.pl

Fix import script to handle sequence alterations and read_through_stop_codons

---

grails-app/domain/org/bbop/apollo/User.groovy
grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy
test/unit/org/bbop/apollo/UserSpec.groovy

Fix remote user auth

---

grails-app/services/org/bbop/apollo/SequenceService.groovy

fixes #1544 to use the specified translation table when getting sequence

---

grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/controllers/org/bbop/apollo/ProjectionGridTrackController.groovy
grails-app/controllers/org/bbop/apollo/ProjectionLegendTrackController.groovy
grails-app/services/org/bbop/apollo/BigwigService.groovy
grails-app/services/org/bbop/apollo/FeatureProjectionService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/NonCanonicalSplitSiteService.groovy
grails-app/services/org/bbop/apollo/ProjectionService.groovy
grails-app/services/org/bbop/apollo/RefSeqProjectorService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy
src/gwt/org/bbop/apollo/gwt/client/projection/ProjectionService.java
src/gwt/org/bbop/apollo/gwt/shared/projection/AbstractProjection.java
src/gwt/org/bbop/apollo/gwt/shared/projection/DiscontinuousProjection.java
src/gwt/org/bbop/apollo/gwt/shared/projection/MultiSequenceProjection.java
src/gwt/org/bbop/apollo/gwt/shared/projection/ProjectionInterface.java
test/unit/org/bbop/apollo/gwt/shared/projection/DiscontinuousProjectionSpec.groovy
test/unit/org/bbop/apollo/gwt/shared/projection/MultiSequenceProjectionSpec.groovy

refactored as part of #1570

---

docs/Configure.md
docs/conf.py
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/RestService.java

Configure extra tab panel

---

grails-app/services/org/bbop/apollo/FeatureService.groovy

Fix bug where generateTranscript was trying to access 'name' from JSONObject when it wasn't there to begin with

---

src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java

Was throwing an error if the preference was not set.  Not ideal.

fixed preference error and default always on for track (before update)

---

grails-app/services/org/bbop/apollo/AssemblageService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/PreferenceService.groovy
sample-docker-apollo-config.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
test/integration/org/bbop/apollo/FeatureProjectionServiceIntegrationSpec.groovy
test/integration/org/bbop/apollo/TrackServiceIntegrationSpec.groovy

Fix fps 1582

---

docs/Web_services.md
grails-app/controllers/org/bbop/apollo/GroupController.groovy
restapidoc.json
web-app/js/restapidoc/restapidoc.json

When you have a moment to look at this.

Document webservice wrapper

---

grails-app/services/org/bbop/apollo/AnnotatorService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy

- optimizes IO for larger instances

sped up annotation collection greatly

---

src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

fixes pipes URL #1606

---

grails-app/services/org/bbop/apollo/AnnotatorService.groovy
grails-app/services/org/bbop/apollo/PreferenceService.groovy

@childers  This should fix adding a user and an organism for the first time.

fixes issue when registering system for the first time and adding organism

---

grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
grails-app/services/org/bbop/apollo/OverlapperService.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
src/groovy/org/bbop/apollo/GFF3Entry.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
test/integration/org/bbop/apollo/SequenceServiceIntegrationSpec.groovy

Extending methods in `Gff3HandlerService` to export GFF3 from projected JSON features.

Extending GFF3 export functionality to support features on an assemblage

---

grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
grails-app/services/org/bbop/apollo/OverlapperService.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
src/groovy/org/bbop/apollo/GFF3Entry.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
test/integration/org/bbop/apollo/SequenceServiceIntegrationSpec.groovy

Revert "Extending GFF3 export functionality to support features on an assemblage"

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/main.js
grails-app/services/org/bbop/apollo/PreferenceService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/AssemblageInfoService.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/assemblage/AssemblageSequenceWidget.java
src/gwt/org/bbop/apollo/gwt/client/dto/assemblage/AssemblageSequence.java

Projection ui refactor - Fixes #1610

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js

Restore 'Pin to top' and 'Delete track' ability for all HTMLFeatures

---

client/apollo/js/View/Track/AnnotTrack.js

Fixes #1631 . 
@deepakunni3  Could you take a look at this.

fixess error when no parent type.  Fixes #1631

---

docs/TestScript.md

Fixes #1623 
This is just a start, but let me know if there are big things missing.
FYI @monicacecilia

Fixes #1623 Fix test script reverse complement

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

fixes #1636 
Sorry, created a new PR.

fixes #1636

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

Fixes #1643. 
FYI @childers  and @deepakunni3

Fix permission errors and fixes 1643

---

grails-app/services/org/bbop/apollo/SequenceService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

Fixes #1646
@deepakunni3  Can you test this to make sure that sequence alterations function correctly still?

Fixes #1646

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/SequenceTrack.js
grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/AnnotationEditorService.groovy
test/unit/org/bbop/apollo/AnnotationEditorServiceSpec.groovy

should fix #1643 when merged, upgrading library

---

client/apollo/js/View/Track/AnnotTrack.js
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

- fixed a js object error and removed login response error popup

fixed a js object error and removed login response error popup

---

client/apollo/js/View/Track/SequenceTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

Fix issues with sequence alterations in reverse complement view

---

src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java

fixed no track category fixes #1661

---

client/apollo/js/main.js
docs/Configure.md
grails-app/conf/Config.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

fixes #1260

---

docs/Configure.md

Based on discussion in #1707
Thanks @childers

updated bad config doc

---

client/apollo/css/maker.css
client/apollo/css/webapollo_track_styles.css
client/apollo/js/View/Track/DraggableHTMLFeatures.js
client/apollo/js/View/Track/SequenceTrack.js

Fix negative strand

---

client/apollo/js/main.js
docs/Data_loading.md
grails-app/services/org/bbop/apollo/FeatureService.groovy

Remove file menu 1713

---

ChangeLog.md

Updating ChangeLog - DoNotMerge

---

grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/services/org/bbop/apollo/TrackService.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

@nathandunn This is ready for test and review.

Support tracks.conf

---

grails-app/controllers/org/bbop/apollo/GroupController.groovy
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy

should fix #1726

---

grails-app/assets/stylesheets/main.css
grails-app/controllers/org/bbop/apollo/FeatureEventController.groovy
grails-app/views/featureEvent/report.gsp
src/gwt/org/bbop/apollo/gwt/client/dto/SequenceInfoConverter.java

fixes #1727

---

grails-app/assets/stylesheets/annotator.css
grails-app/services/org/bbop/apollo/PreferenceService.groovy
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/public/theme.css

fixes #1730 
If you loaded an organism with a lot of tracks Google Chrome was thrashing.  This fixes that.   I hope it still looks nice.

Remove toggle switches 1730

---

docs/web_services/examples/shell/addComment.sh
docs/web_services/examples/shell/deleteFeature.sh
docs/web_services/examples/shell/doLogin.sh
docs/web_services/examples/shell/exportFeatures.sh
docs/web_services/examples/shell/findAllOrganisms.sh
docs/web_services/examples/shell/getFeatures.sh
docs/web_services/examples/shell/loadGroups.sh
docs/web_services/examples/shell/loadUsers.sh
docs/web_services/examples/shell/setStatus.sh

@nathandunn fixed couple of shell scripts that pretty much had some hard coded URLs and username.
Also cleaned up some other scripts as well.

Fix web services examples

---

grails-app/services/org/bbop/apollo/PreferenceService.groovy

was looking things up in the opposite order.  Fixes #1744

---

grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy

fixes #1742
Fixes the case where the Apollo plugin is specified in the `apollo-config.groovy`

fixes #1742

---

grails-app/services/org/bbop/apollo/FeatureEventService.groovy
test/integration/org/bbop/apollo/FeatureEventServiceIntegrationSpec.groovy

handling split / merge history 

---

grails-app/services/org/bbop/apollo/FeatureService.groovy

Here's a patch to fix #1753 
I tested it on our server, and it seems to work fine

Fix sql query when listing alterations

---

grails-app/services/org/bbop/apollo/TrackService.groovy

updated tracked data to work with remote trackData.json and jsonz format

---

build.gradle
grails-app/services/org/bbop/apollo/FeatureService.groovy

Fix build 1756

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

Fix bug where gene boundaries was not being updated after deletion of an isoform

---

.gitignore
apollo
build.gradle
grails-app/conf/Config.groovy
package.json

The current method always pulled master instead of a tag or a branch, which is less than ideal.  
The main reason for ignoring npm was that it complained about not having a top-level package.json.  This should fix that.

Install npm package

---

docs/web_services/examples/shell/listStatus.sh
grails-app/controllers/org/bbop/apollo/AvailableStatusController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy

fixes #1759 
web-services setup with:
```
authentications = [
[
"name":"Remote User Authenticator",
"className":"remoteUserAuthenticatorService",
"active":true,
"params":["default_group": "annotators"]
],
[
"name":"Username Password Authenticator",
"className":"usernamePasswordAuthenticatorService",
"active":true,
"params":[]
]
]
```
FYI @abretaud  
Will fail because the code fails to grab permissions properly.

Fix permissions 1759

---

grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy
src/groovy/org/bbop/apollo/FeaturePositionComparator.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

fixes #1769 . . . gene strand not added

fixes #1769 . . . gene strand not flipped properly when moving to opposite strand

---

client/apollo/css/webapollo_track_styles.css

switched strand colors, fixes #1781

---

docs/Setup.md
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy
src/templates/war/web.xml

Add configuration for increasing buffer size in Tomcat

---

grails-app/controllers/org/bbop/apollo/GroupController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/domain/org/bbop/apollo/GroupOrganismPermission.groovy
grails-app/services/org/bbop/apollo/UserService.groovy

Kind of patches #1797 
This adds a separate field "permissionArray".   I don't want to create a breaking change in 2.0.8.

added permissionArray

---

docs/web_services/examples/shell/loadUsers.sh
grails-app/controllers/org/bbop/apollo/UserController.groovy
scripts/load_users.sh
web-app/js/restapidoc/restapidoc.json

adds the omitEmptyOrganism option per: https://github.com/GMOD/Apollo/pull/1800#issuecomment-342969601

omits empty organisms

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/domain/org/bbop/apollo/Organism.groovy

fixes #1804

---

src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/UserPanel.java

If you load the annotator as admin to any tab BUT the user panel and then go to the user panel, it won't load initially.  This fixes it.

fixes user panel load error

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

fixes #1808

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/bbop/apollo/SequenceController.groovy
grails-app/domain/org/bbop/apollo/SequenceCache.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
web-app/js/restapidoc/restapidoc.json

adds the ability to get sequences using a web-services.

added sequence API

---

docs/Apollo2Build.md

Feel free to push / update link data and merge if it looks correct.

added directories for sample data

---

grails-app/controllers/org/bbop/apollo/TrackController.groovy

fixed cache deletion code

---

docs/Configure.md
grails-app/conf/Config.groovy
grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/AuthController.groovy
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
src/groovy/org/bbop/apollo/JBrowseUrlHandler.groovy

@nathandunn Hopefully this should fix the issue we were seeing with dot notation.
Ready for test and review.

Fix improper interpretation of dot notation from URL

---

client/apollo/js/View/Track/AnnotTrack.js
src/gwt/org/bbop/apollo/gwt/client/Annotator.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

fixes #1846 
Seemed to work for BAM reads, transcripts, and other top-levels.  May need more testing, but it looked like it worked.

allow annotator to be focus on current transcript

---

grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

Merge pseudogene to a gene and delete the pseudogene

---

src/gwt/org/bbop/apollo/gwt/client/RegisterDialog.java
src/gwt/org/bbop/apollo/gwt/client/dto/UserInfo.java
src/gwt/org/bbop/apollo/gwt/client/rest/UserRestService.java

Special character login

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js
client/apollo/js/View/Track/WebApolloAlignments2.js
client/apollo/js/View/Track/WebApolloCanvasFeatures.js
docs/Configure.md

Allow default type 1861, fixes #1861

---

client/apollo/js/View/Track/AnnotTrack.js

fixed for the BAM canvas

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/bbop/apollo/TrackController.groovy
grails-app/services/org/bbop/apollo/TrackService.groovy
web-app/js/restapidoc/restapidoc.json

adds get all tracks method e.g.,  http://localhost:8080/apollo/track/list/Honeybee
for https://github.com/biolink/biolink-api/issues/157

added get all track services method

---

grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/ExonService.groovy
grails-app/services/org/bbop/apollo/NonCanonicalSplitSiteService.groovy

@nathandunn Ready to test and review
Fixes #1879

Fix splice site detection

---

grails-app/services/org/bbop/apollo/SequenceService.groovy

PR for 
https://github.com/GMOD/Apollo/issues/1886

close fasta file from getRawResiduesFromSequenceFasta

---

grails-app/controllers/org/bbop/apollo/GroupController.groovy

* Details: passing a JSONArray through web services, cannot cast String to List

fix bugs on GroupController: updateMembership and updateGroupAdmin

---

src/gwt/org/bbop/apollo/gwt/client/rest/RestService.java

fix #1865
@epaule Does this work?

added accept header to fix #1865

---

grails-app/services/org/bbop/apollo/ExonService.groovy

Ensure that string comparison is done in lower-case when finding splice sites

---

application.properties
grails-app/controllers/org/bbop/apollo/AvailableStatusController.groovy

Fix delete status fixes 1909

---

docs/web_services/examples/groovy/delete_annotations_from_sequences.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/OrganismService.groovy
web-app/js/restapidoc/restapidoc.json

Fix sequences

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/AnnotationEditorService.groovy
web-app/js/restapidoc/restapidoc.json

Hi,
I have created a new REST endpoint that would be useful in our automated monitoring of apollo annotation. It returns the genes updated in the last 24 hour. I have added this code to AnnotationEditorController and AnnotationEditorService please advice if there is a better place.
Regards,
Mikkel Christensen

adding new REST endpoint getTodaysAnnotation

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy

fixes #1942 
Needs to support:  https://apollo.genedb.org/7383/jbrowse/index.html?loc=REV3&tracks=DNA%2CAnnotations%2Cgene%2CmRNA&highlight=

WIP - allows URL to contain a symbol name instead of a location -- nomerge

---

client/apollo/css/webapollo_track_styles.css
client/apollo/js/SequenceOntologyUtils.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js
client/apollo/js/View/Track/WebApolloCanvasFeatures.js
client/apollo/json/annot.json
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/domain/org/bbop/apollo/Terminator.groovy
grails-app/services/org/bbop/apollo/ChadoHandlerService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/FeatureTypeService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java

added terminator

---

grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

added status to return json

---

apollo

description at https://github.com/GMOD/Apollo/issues/1993#issue-392072877

fix for issue 1993 (yarn version check not working)

---

client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLVariants.js

fixes #2005 and a mouse-down bug

fixes problem with soft masking and variant mouse-down

---

.travis.yml
client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/ReportService.groovy
grails-app/services/org/bbop/apollo/authenticator/UsernamePasswordAuthenticatorService.groovy

fixes a few small bug fixes affecting performance and logging.

Add report fixes v1

---

apollo
build.gradle

fix for #2017

---

src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml

fixes #1968

---

grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

Add multiple gff3 owners

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy

fixes deletion of output files

---

client/apollo/css/webapollo_track_styles.css
client/apollo/js/View/Track/DraggableAlignments.js
grails-app/assets/stylesheets/main.css

first pass to begin fixing CSS

---

client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js

create exons from cigarstring matches

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
src/gwt/org/bbop/apollo/gwt/client/Annotator.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.java
src/gwt/org/bbop/apollo/gwt/client/SequencePanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfo.java
src/gwt/org/bbop/apollo/gwt/client/rest/AnnotationRestService.java
web-app/js/restapidoc/restapidoc.json

fixed the styling and cleaned up a bit

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy

added the initial commit

---

client/apollo/css/webapollo_track_styles.css
client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy

added coordinates

---

client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js

Addresses #2052 and also fixes a small bug where the `generateSubFeaturesFromCigar` function wasn't correctly pulling out strand information.

Modify with cigar

---

client/apollo/js/JSONUtils.js

fixes subfeature annotation 

---

docs/TestScript.md
grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/FileService.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
grails-app/services/org/bbop/apollo/TrackService.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy
src/groovy/org/bbop/apollo/track/TrackDefaults.groovy
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
src/gwt/org/bbop/apollo/gwt/shared/track/SequenceTypeEnum.java
src/gwt/org/bbop/apollo/gwt/shared/track/TrackIndex.java
web-app/js/restapidoc/restapidoc.json

added most of the base components

---

client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js

Fix 2085 indel

---

client/apollo/js/View/Track/DraggableHTMLFeatures.js

This PR + https://github.com/GMOD/jbrowse/pull/1343 seems to be enough to fix #2099

Fix block detection with inferHTMLSubfeatures (fixes #2099)

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/JbrowseHandlerService.groovy
src/gwt/org/bbop/apollo/gwt/client/ExportPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java

started to stub code for downloading

---

grails-app/services/org/bbop/apollo/SequenceService.groovy

rewriting correctly, but not getting text write

---

grails-app/domain/org/bbop/apollo/FeatureProperty.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy

patching with fix #267

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/TrackService.groovy
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java
src/gwt/org/bbop/apollo/gwt/client/TrackPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/track/TrackConfigurationTemplate.java

fixed the UI to use the proper top type

---

client/apollo/js/JSONUtils.js
client/apollo/js/SequenceOntologyUtils.js

automatically infers shine dalgarno track now

---

src/gwt/org/bbop/apollo/gwt/client/GroupPanel.java
src/gwt/org/bbop/apollo/gwt/client/GroupPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml

Fix 2081 searchable org group

---

grails-app/conf/BootStrap.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
web-app/js/restapidoc/restapidoc.json

adds blat upload option

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/OrganismService.groovy
test/unit/org/bbop/apollo/OrganismServiceSpec.groovy
web-app/js/restapidoc/restapidoc.json

Fix 2082 v2

---

docs/Setup.md

fixes #2222
@jasonsydes does this look good?

clarifies JAVA_HOME instructions

---

grails-app/domain/org/bbop/apollo/Feature.groovy
grails-app/domain/org/bbop/apollo/FeatureProperty.groovy
grails-app/domain/org/bbop/apollo/Publication.groovy
grails-app/services/org/bbop/apollo/FeaturePropertyService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy

added more duplications

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy

I'm finally testing #2227 to update organism by uploading an archive
Just a typo in a variable name, + a (probably?) missing line in the archive handling
For some reason, the upload seems to fail even with these changes, I get this error:
```
{
"error": "problem saving organism: java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class java.io.File"
}
```
I'm trying to get more details, any idea?

Remote organism update fix

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy

So I've tested the last commit of #2245, and there was an error, so here's a fix

Fix error in remote org update

---

grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy

fixes some of the errors due to rest API request

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/SequenceService.groovy
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/OrganismRestService.java

related to #2249 and #2250 and #2248

guards against changing directory

---

client/apollo/js/SequenceSearch.js
client/apollo/js/View/Track/AnnotTrack.js

minor blat improvements

---

grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
src/gwt/org/bbop/apollo/gwt/client/ExportPanel.java
src/gwt/org/bbop/apollo/gwt/client/SearchPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/SequenceRestService.java
src/gwt/org/bbop/apollo/gwt/shared/sequence/SearchHit.java

saves as FASTA . . fixes #2263

---

src/gwt/org/bbop/apollo/gwt/client/SearchPanel.java
src/gwt/org/bbop/apollo/gwt/client/rest/AnnotationRestService.java
src/gwt/org/bbop/apollo/gwt/shared/sequence/SearchHit.java

creating annotation properly now

---

.travis.yml
apollo
src/groovy/org/bbop/apollo/sequence/search/blast/BlastAlignment.java

allowed for node 12 and added tests for all

---

grails-app/conf/org/bbop/apollo/SecurityFilters.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.ui.xml

fixes #2275 by catching type mismatch errors properly

---

README.md
docs/Apollo2Build.md
docs/Architecture.md
docs/Setup.md
docs/index.rst

updated documentation into better sections

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/domain/org/bbop/apollo/Organism.groovy
grails-app/services/org/bbop/apollo/DomainMarshallerService.groovy

fixes #2290 possibly
FYI @abretaud

possibly fixes #2290

---

Dockerfile

build docker from current source

---

.travis.yml

this way it won't affect other tests and maybe mark them as failed if it isn't necessary?

Separate test against postgres+python-apollo, not in main code path

---

client/apollo/js/View/Track/AnnotTrack.js
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/RepeatRegionDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/RepeatRegionDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/VariantDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/VariantDetailPanel.ui.xml

Fix 2338 uniquenamesearch

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java

almost working to not change context on transciprt open edit

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/domain/org/bbop/apollo/Feature.groovy
grails-app/domain/org/bbop/apollo/FeatureSynonym.groovy
grails-app/domain/org/bbop/apollo/Synonym.groovy
grails-app/migrations/changelog-2_6_0.groovy
grails-app/migrations/changelog.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
grails-app/services/org/bbop/apollo/GpiHandlerService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/RepeatRegionDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/VariantDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/VariantDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfo.java
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfoConverter.java
src/gwt/org/bbop/apollo/gwt/client/rest/AnnotationRestService.java

moved synonyms so a singular place to store

---

grails-app/controllers/org/bbop/apollo/IOServiceController.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy

returns both non-coding ncRNA and mRNA without duplication

---

grails-app/services/org/bbop/apollo/VcfService.groovy

fixes #2376

---

Dockerfile
docker-files/launch.sh

fixes #2373

---

grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java

added gff3 fixes #2371

---

Dockerfile
docker-files/createenv.sh
docker-files/launch.sh
docs/Troubleshooting.md

starting to build out for postgresql 9.6

---

grails-app/controllers/org/bbop/apollo/geneProduct/GeneProductController.groovy
grails-app/services/org/bbop/apollo/geneProduct/GeneProductService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/dto/GeneProductConverter.java
web-app/js/restapidoc/restapidoc.json

fixed REST api doc and switched

---

client/apollo/js/View/Track/AnnotTrack.js
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/SearchPanel.java

fixes #2395 by fixing lookups

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/ExonDetailPanel.java

added annotation description

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/services/org/bbop/apollo/FileService.groovy

able to gunzip gff data

---

client/apollo/js/View/Track/AnnotTrack.js

fixes #2446 fixes #2453 fixes #2448

---

client/apollo/js/JSONUtils.js
client/apollo/js/View/Track/AnnotTrack.js
client/apollo/js/View/Track/DraggableHTMLFeatures.js
client/apollo/js/View/Track/WebApolloAlignments2.js
client/apollo/js/View/Track/WebApolloCanvasFeatures.js
client/apollo/json/annot.json
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/domain/org/bbop/apollo/EnzymaticRNA.groovy
grails-app/domain/org/bbop/apollo/GuideRNA.groovy
grails-app/domain/org/bbop/apollo/LncRNA.groovy
grails-app/domain/org/bbop/apollo/PiRNA.groovy
grails-app/domain/org/bbop/apollo/ProcessedPseudogene.groovy
grails-app/domain/org/bbop/apollo/PseudogenicRegion.groovy
grails-app/domain/org/bbop/apollo/RNaseMRPRNA.groovy
grails-app/domain/org/bbop/apollo/RNasePRNA.groovy
grails-app/domain/org/bbop/apollo/ScRNA.groovy
grails-app/domain/org/bbop/apollo/SrpRNA.groovy
grails-app/domain/org/bbop/apollo/TelomeraseRNA.groovy
grails-app/domain/org/bbop/apollo/TmRNA.groovy
grails-app/services/org/bbop/apollo/ChadoHandlerService.groovy
grails-app/services/org/bbop/apollo/FastaHandlerService.groovy
grails-app/services/org/bbop/apollo/FeatureService.groovy
grails-app/services/org/bbop/apollo/FeatureTypeService.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy
grails-app/services/org/bbop/apollo/geneProduct/GeneProductService.groovy
grails-app/services/org/bbop/apollo/go/GoAnnotationService.groovy
grails-app/services/org/bbop/apollo/provenance/ProvenanceService.groovy
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

fixes #2392 
Steps to do:
---
---
Types to add:
Added psuedogene types:
---
(already included) 
to describe the transcript, so I'm guessing the sub-classes would be:
---

add extra SO types

---

client/apollo/js/View/Track/DraggableHTMLFeatures.js
grails-app/domain/org/bbop/apollo/GuideRNA.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy
test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy

fixes to transcript errors

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/views/annotator/index.gsp
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

fixes #2444

---

ChangeLog.md
docker-files/docker-apollo-config.groovy
docs/Configure.md
grails-app/conf/Config.groovy
grails-app/services/org/bbop/apollo/AnnotatorService.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy

fixes #2414

---

docker-files/docker-apollo-config.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy

fixes #2479

---

src/gwt/org/bbop/apollo/gwt/client/GeneProductPanel.java
src/gwt/org/bbop/apollo/gwt/client/GoPanel.java
src/gwt/org/bbop/apollo/gwt/client/ProvenancePanel.java
src/gwt/org/bbop/apollo/gwt/client/oracles/BiolinkOntologyOracle.java

 fixed some links

---

.travis.yml
grails-app/controllers/org/bbop/apollo/UserController.groovy
test/config/run-travis.sh

fixes #2494

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/OrganismService.groovy
src/groovy/org/bbop/apollo/sequence/SequenceTranslationHandler.groovy
test/unit/org/bbop/apollo/TranslationTableSpec.groovy

fixes #2504 
If this doesn't work, we should inline

use webroot for path to handle translation tables 

---

grails-app/controllers/org/bbop/apollo/OrganismController.groovy

add returnAllOrganisms to updateOrganismWithInfo

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.ui.xml

works on the gene page

---

grails-app/controllers/org/bbop/apollo/VcfController.groovy

fix for https://agr-jira.atlassian.net/browse/AGR-2449

fix encoding to match cache

---

src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/TranscriptDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/dto/AnnotationInfoConverter.java
src/gwt/org/bbop/apollo/gwt/client/rest/AnnotationRestService.java

for smaller sets of genes is working

---

ChangeLog.md
grails-app/controllers/org/bbop/apollo/GeneProductController.groovy
grails-app/controllers/org/bbop/apollo/GoAnnotationController.groovy
grails-app/controllers/org/bbop/apollo/ProvenanceController.groovy
web-app/js/restapidoc/restapidoc.json

Added missing top-level annotation to make GO, Gene Product, and Provenance visible.

added missing annotations

---

ChangeLog.md
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.java
src/gwt/org/bbop/apollo/gwt/client/OrganismPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/shared/OrganismComparator.java

added genus and species to drop-down with common name

---

ChangeLog.md
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
src/gwt/org/bbop/apollo/gwt/client/MainPanel.java

added a UUID based link

---

ChangeLog.md
docs/web_services/examples/shell/getRecent.sh
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/AnnotationEditorService.groovy
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.java
src/gwt/org/bbop/apollo/gwt/client/GeneDetailPanel.ui.xml
web-app/js/restapidoc/restapidoc.json

should fix filtering of statuses

---

ChangeLog.md
docs/Configure.md
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy

added location feature name which fixes #2544

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
web-app/js/restapidoc/restapidoc.json

fixes #2556

---

grails-app/controllers/org/bbop/apollo/SequenceController.groovy
web-app/js/restapidoc/restapidoc.json

fixes #2555

---

ChangeLog.md
docker-files/docker-apollo-config.groovy
docs/Configure.md
grails-app/conf/Config.groovy
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy
grails-app/services/org/bbop/apollo/PermissionService.groovy
grails-app/services/org/bbop/apollo/TranscriptService.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy

fixes #2567 and a small security fix

fixes #2567

---

ChangeLog.md
grails-app/controllers/org/bbop/apollo/JbrowseController.groovy
grails-app/controllers/org/bbop/apollo/TrackController.groovy

allow overlap filter to be configurable

---

ChangeLog.md
grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy

fixes annotation editor controller

---

ChangeLog.md
src/gwt/org/bbop/apollo/gwt/client/dto/GeneProductConverter.java
src/gwt/org/bbop/apollo/gwt/client/dto/GoAnnotationConverter.java
src/gwt/org/bbop/apollo/gwt/client/dto/ProvenanceConverter.java

fixes #2595

---

ChangeLog.md
grails-app/controllers/org/bbop/apollo/TrackController.groovy
web-app/js/restapidoc/restapidoc.json

fixes https://agr-jira.atlassian.net/browse/AGR-2687?utm_source=trello&utm_content=trello-smartlink&utm_campaign=trello-smartlink-v2

added unique flag

---

grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
grails-app/controllers/org/bbop/apollo/OrganismController.groovy
grails-app/controllers/org/bbop/apollo/UserController.groovy
grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
src/gwt/org/bbop/apollo/gwt/shared/FeatureStringEnum.java
src/gwt/org/bbop/apollo/gwt/shared/track/SequenceTypeEnum.java
web-app/js/restapidoc/restapidoc.json

To support this:
https://github.com/GMOD/apollo-gmod-js/pull/54

small adjustments for functional tests

---

ChangeLog.md
grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
src/gwt/org/bbop/apollo/gwt/client/UploadDialog.java
src/gwt/org/bbop/apollo/gwt/client/rest/GeneProductRestService.java
src/gwt/org/bbop/apollo/gwt/client/rest/GoRestService.java
src/gwt/org/bbop/apollo/gwt/client/rest/ProvenanceRestService.java

- Fixes bad syntax for WithOrFrom for Go annotations
- Handles having a missing annotations types in JSON uploads
- adds another JSON example

Fix json attribute upload

---

grails-app/conf/BuildConfig.groovy

See https://github.com/grails/grails-core/issues/11825

Update mavenRepo to fix grails error

---

docs/Docker.md

A very small change to fix a broken link.

Fix broken link to Docker launch.sh file
